/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
require({cache:{"url:esri/dijit/templates/LayerSwipe.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation"\x3e\r\n    \x3cdiv title\x3d"${_i18n.widgets.layerSwipe.title}" data-dojo-attach-point\x3d"_moveableNode"\x3e\r\n        \x3cdiv class\x3d"${_css.handleContainer}"\x3e\r\n            \x3cdiv class\x3d"${_css.handle}"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/LayerSwipe","dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has esri/kernel dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dojo/on dojo/text!esri/dijit/templates/LayerSwipe.html dojo/i18n!esri/nls/jsapi dojo/dom-class dojo/dom-style dojo/dnd/move dojo/dnd/Mover dojo/sniff dojo/dom-geometry esri/geometry/Point esri/geometry/Extent dojo/dom-construct dojo/Deferred dojo/promise/all".split(" "),function(q,v,l,z,A,B,C,D,m,E,F,u,r,w,G,s,n,p,H,I,y,J){var x=v([G],
{onFirstMove:function(b){var a=this.node.style,d,e=this.host;switch(a.position){case "relative":case "absolute":d=Math.round(parseFloat(a.left))||0;a=Math.round(parseFloat(a.top))||0;break;default:a.position="absolute",a=n.getMarginBox(this.node),d=a.l,a=a.t}this.marginBox.l=d-this.marginBox.l;this.marginBox.t=a-this.marginBox.t;if(e&&e.onFirstMove)e.onFirstMove(this,b);this.events.shift().remove()}});q=v([B,C,D,q],{declaredClass:"esri.dijit.LayerSwipe",templateString:E,options:{theme:"LayerSwipe",
map:null,layers:[],enabled:!0,type:"vertical",clip:9,top:null,left:null},constructor:function(b,a){v.safeMixin(this.options,b);this.domNode=a;this._i18n=F;this.set("map",this.options.map);this.set("layers",this.options.layers);this.set("top",this.options.top);this.set("left",this.options.left);this.set("theme",this.options.theme);this.set("enabled",this.options.enabled);this.set("type",this.options.type);this.set("clip",this.options.clip);this.watch("theme",this._updateThemeWatch);this.watch("enabled",
this._enabled);this.watch("type",this._type);this._css={handleContainer:"handleContainer",handle:"handle"};this._listeners=[]},startup:function(){this.map||(this.destroy(),console.log("LayerSwipe::map required"));for(var b=[],a=0;a<this.layers.length;a++)if("string"===typeof this.layers[a]&&(this.layers[a]=this.map.getLayer(this.layers[a]),!this.layers[a].loaded)){var d=new y;this._layerLoadedPromise(a,d);b.push(d)}this.set("layers",this.layers);this.layers.length||(this.destroy(),console.log("LayerSwipe::layer required"));
if(!this.map.loaded){var e=new y;m.once(this.map,"load",l.hitch(this,function(){e.resolve("map loaded")}));b.push(e)}b.length?J(b).then(l.hitch(this,function(){this._init()})):this._init()},destroy:function(){this._removeEvents();this.inherited(arguments)},swipe:function(){this._setClipValue();this._swipe()},enable:function(){this.set("enabled",!0)},disable:function(){this.set("enabled",!1)},_layerLoadedPromise:function(b,a){m.once(this.layers[b],"load",function(){a.resolve("layer loaded")})},_mb:function(){var b=
n.getMarginBox(this.map.root),a={t:0,l:0};a.w=b.l+b.w;a.h=b.h+b.t;return a},_setSwipeType:function(){var b,a;this.get("type")&&(this._swipeslider&&this._swipeslider.destroy(),u.add(this._moveableNode,this.get("type")),b=n.getMarginBox(this._moveableNode),"scope"===this.get("type")?(this._swipeslider=new w.constrainedMoveable(this._moveableNode,{handle:this._moveableNode.id,constraints:l.hitch(this,this._mb),within:!0,mover:x}),a=this.map.width/2-b.w/2,b=this.map.height/2-b.h/2,this.get("top")&&(b=
this.get("top")),this.get("left")&&(a=this.get("left"))):"horizontal"===this.get("type")?(this._swipeslider=new w.parentConstrainedMoveable(this._moveableNode,{area:"content",within:!0,mover:x}),a=0,b=this.map.height/4-b.h/2,this.get("top")&&(b=this.get("top")),this._clipval=b):(this._swipeslider=new w.parentConstrainedMoveable(this._moveableNode,{area:"content",within:!0,mover:x}),a=this.map.width/4-b.w/2,b=0,this.get("left")&&(a=this.get("left")),this._clipval=a),r.set(this._moveableNode,{top:b+
"px",left:a+"px"}))},_init:function(){this._setSwipeType();I.place(this.domNode,this.map._layersDiv,"last");this._swipe();this._setupEvents();this.set("loaded",!0);this.emit("load",{})},_removeEvents:function(){if(this._listeners.length)for(var b=0;b<this._listeners.length;b++)this._listeners[b].remove();this._listeners=[]},_setClipValue:function(){var b=n.getMarginBox(this._moveableNode);if("vertical"===this.get("type")){var a=b.l;if(0>=a||a>=this.map.width)return;this._clipval=a}"horizontal"===
this.get("type")&&(b=b.t,0>=b||b>=this.map.height||(this._clipval=b))},_setupEvents:function(){this._removeEvents();this._swipeMove=m.pausable(this._swipeslider,"Move",l.hitch(this,function(){this._setClipValue();this._swipe()}));this._listeners.push(this._swipeMove);this._swipePanEnd=m.pausable(this.map,"pan-end",l.hitch(this,function(){this._swipe()}));this._listeners.push(this._swipePanEnd);this._mapUpdateEnd=m.pausable(this.map,"update-end",l.hitch(this,function(){this._swipe()}));this._listeners.push(this._mapUpdateEnd);
"css-transforms"===this.map.navigationMode&&(this._swipePan=m.pausable(this.map,"pan",l.hitch(this,function(){this._swipe()})),this._listeners.push(this._swipePan));this._toolClick=m.pausable(this._moveableNode,"click",l.hitch(this,function(b){if(this.map.hasOwnProperty("onClick")&&"function"===typeof this.map.onClick&&this._clickCoords&&this._clickCoords.x===b.x&&this._clickCoords.y===b.y){var a=n.position(this.map.root,!0),d=b.pageX-a.x,a=b.pageY-a.y;b.x=d;b.y=a;b.screenPoint={x:d,y:a};b.type="click";
b.mapPoint=this.map.toMap(new p(d,a,this.map.spatialReference));this.map.onClick(b,"other")}this._clickCoords=null}));this._listeners.push(this._toolClick);this._evtCoords=m.pausable(this._swipeslider,"MouseDown",l.hitch(this,function(b){this._clickCoords={x:b.x,y:b.y}}));this._listeners.push(this._evtCoords)},_swipe:function(){for(var b={layers:[]},a=0;a<this.layers.length;a++){var d,e,h,f,c=null,g,l=null;"vertical"===this.get("type")?(n.getMarginBox(this._moveableNode),this.layers[a]._div&&(c=n.getMarginBox(this.layers[a]._div)),
g=n.getMarginBox(this.map.root),c&&0<c.l?(d=this._clipval-Math.abs(c.l),e=-c.l):c&&0>c.l?(e=0,d=this._clipval+Math.abs(c.l)):(e=0,d=this._clipval),c&&0<c.t?(h=-c.t,f=g.h-c.t):c&&0>c.t?(h=0,f=g.h+Math.abs(c.t)):(h=0,f=g.h)):"horizontal"===this.get("type")?(n.getMarginBox(this._moveableNode),this.layers[a]._div&&(c=n.getMarginBox(this.layers[a]._div)),g=n.getMarginBox(this.map.root),c&&0<c.t?(f=this._clipval-Math.abs(c.t),h=-c.t):c&&0>c.t?(h=0,f=this._clipval+Math.abs(c.t)):(h=0,f=this._clipval),c&&
0<c.l?(e=-c.l,d=g.w-c.l):c&&0>c.l?(e=0,d=g.w+Math.abs(c.l)):(e=0,d=g.w)):"scope"===this.get("type")&&(f=n.getMarginBox(this._moveableNode),e=f.l,d=e+f.w,h=f.t,f=h+f.h,this.clip&&(e+=this.clip,d+=-this.clip,h+=this.clip,f+=-this.clip));if(this.layers[a].graphics&&this.layers[a].graphics.length){var m,t;"vertical"===this.get("type")?(m=this.map.toMap(new p(0,this.map.height,this.map.spatialReference)),t=this.map.toMap(new p(this._clipval,0,this.map.spatialReference))):"horizontal"===this.get("type")?
(m=this.map.toMap(new p(0,this._clipval,this.map.spatialReference)),t=this.map.toMap(new p(this.map.width,0,this.map.spatialReference))):"scope"===this.get("type")&&(m=this.map.toMap(new p(e,f,this.map.spatialReference)),t=this.map.toMap(new p(d,h,this.map.spatialReference)));if(l=new H(m.x,m.y,t.x,t.y,this.map.spatialReference))for(c=0;c<this.layers[a].graphics.length;c++){g=this.layers[a].graphics[c];var k="point"===g.geometry.type?g.geometry:g.geometry.getExtent().getCenter();l.contains(k)?g.show():
g.hide()}}else if(this.layers[a]._div&&"undefined"!==typeof d&&"undefined"!==typeof e&&"undefined"!==typeof h&&"undefined"!==typeof f){g=c=0;if("css-transforms"===this.map.navigationMode&&(k="",s("webkit")&&(k="-webkit-"),s("ff")&&(k="-moz-"),s("ie")&&(k="-ms-"),s("opera")&&(k="-o-"),k=this.layers[a]._div.style.getPropertyValue(k+"transform"))){-1!==k.toLowerCase().indexOf("translate3d")?k=k.replace("translate3d(","").replace(")","").replace(/px/ig,"").replace(/\s/i,"").split(","):-1!==k.toLowerCase().indexOf("translate")&&
(k=k.replace("translate(","").replace(")","").replace(/px/ig,"").replace(/\s/i,"").split(","));try{c=parseFloat(k[0]),g=parseFloat(k[1])}catch(q){console.error(q)}e-=c;d-=c;h-=g;f-=g}r.set(this.layers[a]._div,"clip","rect("+h+"px "+d+"px "+f+"px "+e+"px)")}b.layers.push({layer:this.layers[a],left:e,right:d,top:h,bottom:f,extent:l})}this.emit("swipe",b)},_updateThemeWatch:function(b,a,d){u.remove(this.domNode,a);u.add(this.domNode,d)},_type:function(b,a){a&&u.remove(this._moveableNode,a);this._setSwipeType();
this._enabled()},_enabled:function(){if(this.get("enabled"))this._setupEvents(),this._setClipValue(),this._swipeMove.resume(),this._swipePanEnd.resume(),this._evtCoords.resume(),this._toolClick.resume(),this._mapUpdateEnd.resume(),this._swipePan&&this._swipePan.resume(),r.set(this.domNode,"display","block"),this._swipe();else{this._swipeMove.pause();this._swipePanEnd.pause();this._evtCoords.pause();this._toolClick.pause();this._mapUpdateEnd.pause();this._swipePan&&this._swipePan.pause();r.set(this.domNode,
"display","none");for(var b=0;b<this.layers.length;b++)if(this.layers[b]._div){var a=s("ie")?"rect(auto auto auto auto)":"";r.set(this.layers[b]._div,"clip",a)}}}});z("extend-esri")&&l.setObject("dijit.LayerSwipe",q,A);return q});