/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/arcgis/Portal","dojo/_base/declare dojo/_base/lang dojo/_base/kernel dojo/_base/Deferred dojo/_base/array dojo/_base/sniff dojo/Evented dojo/DeferredList esri/kernel esri/lang esri/request esri/IdentityManager".split(" "),function(f,c,w,m,g,x,y,B,t,z,A){var e={options:{disableIdentityLookup:!0},requestParams:{f:"json"}},k=function(a){function d(d){a[d]||(a[d]=function(){var c=arguments;return m.when(a,function(a){Array.prototype.unshift.call(c,a.results||a);return k(g[d].apply(g,c))})})}
if(!a)return a;a.then&&(a=c.delegate(a));a.total||(a.total=m.when(a,function(a){return z.isDefined(a.total)?a.total:a.length||0}));d("forEach");d("filter");d("map");d("some");d("every");return a},b={useSSL:function(a,d){return-1!==a.indexOf("https:")||e.self&&e.self.allSSL?d.replace("http:","https:"):d},formatUrl:function(a){var d=e.loggedInUser&&e.loggedInUser.credential&&e.loggedInUser.credential.token;return-1!==a.indexOf("null")?null:b.useSSL(window.location.protocol,d?a+(-1!==a.indexOf("?")?
"\x26":"?")+("token\x3d"+d):a)},resultsToTypedArray:function(a,d,b){b=b?b.listings||b.notifications||b.userInvitations||b.tags||b.items||b.groups||b.comments||b.results||b:[];return g.map(b,function(b){b=c.mixin(b,d||{});return a?new a(b):b})},clearFieldsFromObject:function(a,d){var b,e=a.length;if(c.isArray(a))for(b=0;b<e;b++)delete d[a[b]];else for(b in a)delete d[b];return d},requestToTypedArray:function(a,d,e,f,g){return k(b.request(a,d,e).then(c.partial(b.resultsToTypedArray,f,g)))},request:function(a,
d,h){d&&d.portal&&delete d.portal;d=c.mixin(c.mixin({},d||{}),e.requestParams);h=c.mixin(h||{},e.options);return A({url:b.useSSL(window.location.protocol,a.url||a),content:d,callbackParamName:"callback",timeout:h&&h.timeout||0},h)},formatQueryParams:function(a,b,h){a=c.mixin(c.mixin({},a),c.isString(b)?{q:b}:b||{});a.q=!h&&e.extraQuery?"("+a.q+")"+e.extraQuery:a.q;return a}},n=f([],{declaredClass:"esri.arcgis.PortalComment",constructor:function(a){c.mixin(this,a);this.url=this.item.itemUrl+"/comments/"+
this.id;this.created=this.created?new Date(this.created):null}}),p=f([],{declaredClass:"esri.arcgis.PortalRating",constructor:function(a){c.mixin(this,a);this.url=this.item.itemUrl+"/rating";this.created=this.created?new Date(this.created):null}}),l=f([],{declaredClass:"esri.arcgis.PortalItem",constructor:function(a){c.mixin(this,a);this.folderId=this.ownerFolder||this.folderId;this.itemUrl=(this.portal&&this.portal.portalUrl)+"content/items/"+this.id;this.userItemUrl=this.itemUrl.replace("content",
"content/users/"+this.owner+(this.folderId?"/"+this.folderId:""));this.itemDataUrl=b.formatUrl(this.itemUrl+"/data");this.thumbnailUrl=b.formatUrl(this.itemUrl+"/info/"+this.thumbnail);this.created=this.created?new Date(this.created):null;this.uploaded=this.uploaded?new Date(this.uploaded):null;this.modified=this.modified?new Date(this.modified):null},addComment:function(a){var d=c.isString(a)?{comment:a}:a;return b.request(this.itemUrl+"/addComment",d,{usePost:!0}).then(c.hitch(this,function(a){return n(c.mixin(d,
{id:a.commentId,item:this}))}))},updateComment:function(a){if(a&&a.url&&a.comment)return b.request(a.url+"/update",{comment:a.comment},{usePost:!0}).then(function(b){a.id=b.commentId;return a});throw Error();},getComments:function(){return b.requestToTypedArray(this.itemUrl+"/comments",null,null,n,{item:this})},deleteComment:function(a){if(a&&a.url)return b.request(a.url+"/delete",null,{usePost:!0});throw Error();},addRating:function(a){var d=c.isObject(a)?a:{rating:parseFloat(a)};return b.request(this.itemUrl+
"/addRating",d,{usePost:!0}).then(c.hitch(this,function(a){return new p(c.mixin(d,{id:a.ratingId,item:this}))}))},getRating:function(){return b.request(this.itemUrl+"/rating").then(c.hitch(this,function(a){return new p(c.mixin(a,{item:this}))}))},deleteRating:function(){return b.request(this.itemUrl+"/deleteRating",null,{usePost:!0})}}),q=f([],{declaredClass:"esri.arcgis.PortalListing",constructor:function(a){c.mixin(this,a);this.id=this.itemId;this.url=(this.portal&&this.portal.portalUrl)+"content/"+
(this.userItemUrl?"items/":"listings/")+this.itemId;this.commentsUrl=this.url+"/comments";this.created=this.created?new Date(this.created):null;this.banner=this.banner?b.formatUrl(this.url+"/info/"+this.banner):"";this.thumbnail=this.thumbnail?b.formatUrl(this.url+"/info/"+this.thumbnail):"";this.largeThumbnail=this.largeThumbnail?b.formatUrl(this.url+"/info/"+this.largeThumbnail):"";this.avgRating=this.avgRating||0;this.numRatings=this.numRatings||0;this.numComments=this.numComments||0;this.listingProperties=
this.listingProperties||{priceDesc:"",creditsPerTransaction:0,licenseType:"free",trialSupported:!1,trialDuration:0,listingAccess:"private"};for(var d in this.listingProperties)this[d]&&(this.listingProperties[d]=this[d]);this.properties=this.properties||{systemRequirements:"",termsAndConditions:"",version:"1.0"};this.screenshots=g.map(this.screenshots,c.hitch(this,function(a){return b.formatUrl(this.url+"/info/"+a)}));this.vendorName=this.vendor.name;this.vendor.orgPhone=this.vendor.orgPhone;this.vendor.orgEmail=
this.vendor.orgEmail;this.vendor.orgUrl=this.vendor.orgUrl;this.vendor.description=this.vendor.description;this.vendor.thumbnail=this.vendor.thumbnail?this.userItemUrl?b.formatUrl(this.portal.portalUrl+"/accounts/self/resources/"+this.vendor.thumbnail):b.formatUrl(this.url+"/vendorinfo/"+this.vendor.thumbnail):""},getComments:function(){return b.requestToTypedArray(this.commentsUrl,null,null,n,{item:this})},getVendor:function(){return this.vendor}}),r=f([],{declaredClass:"esri.arcgis.PortalProvision",
constructor:function(a){c.mixin(this,a);this.created=this.created?new Date(this.created):null;this.startDate=this.startDate?new Date(this.startDate):null;this.endDate=this.endDate&&-1!==this.endDate?new Date(this.endDate):null;this.listing=a.listing?new q(c.mixin(a.listing,{portal:this.portal})):null}}),s=f([],{declaredClass:"esri.arcgis.PortalGroup",constructor:function(a){c.mixin(this,a);this.url=(this.portal&&this.portal.portalUrl)+"community/groups/"+this.id;this.thumbnailUrl=b.formatUrl(this.url+
"/info/"+this.thumbnail);this.modified=this.modified?new Date(this.modified):null;this.created=this.created?new Date(this.created):null},getMembers:function(){return b.request(this.url+"/users")},queryItems:function(a){a=b.formatQueryParams({},a);a.q="group:"+this.id+(a.q?" "+a.q:"");return this.portal.queryItems(a)}}),u=f([],{declaredClass:"esri.arcgis.PortalFolder",constructor:function(a){c.mixin(this,a);this.url=(this.portal&&this.portal.portalUrl)+"content/users/"+this.username+"/"+this.id;this.created=
this.created?new Date(this.created):null},getItems:function(){return b.requestToTypedArray(this.url,null,null,l,{portal:this.portal,folderId:this.id})}}),v=f([],{declaredClass:"esri.arcgis.PortalUser",constructor:function(a){c.mixin(this,a);this.url=(this.portal&&this.portal.portalUrl)+"community/users/"+this.username;this.userContentUrl=(this.portal&&this.portal.portalUrl)+"content/users/"+this.username;this.thumbnailUrl=b.formatUrl(this.url+"/info/"+this.thumbnail);this.modified=this.modified?new Date(this.modified):
null;this.created=this.created?new Date(this.created):null},getGroups:function(){return k(b.request(this.url).then(c.hitch(this,function(a){return b.resultsToTypedArray(s,{portal:this.portal},a.groups)})))},getNotifications:function(){return b.requestToTypedArray(this.url+"/notifications",null,null,null,{portal:this.portal})},getGroupInvitations:function(){return b.requestToTypedArray(this.url+"/invitations",null,null,null,{portal:this.portal})},getTags:function(){return b.requestToTypedArray(this.url+
"/tags",null,null,null,{portal:this.portal})},getFolders:function(){return k(this.getContent().then(function(a){return a.folders}))},getItems:function(a){return k(this.getContent(a).then(function(a){return a.items}))},getItem:function(a){return b.request(this.portal.portalUrl+"content/items/"+a).then(c.hitch(this,function(a){return new l(c.mixin(a,{portal:this.portal}))}))},getContent:function(a){var d=this.url.replace("community","content")+(a?"/"+a:"");return b.request(d).then(c.hitch(this,function(d){d.folders=
b.resultsToTypedArray(u,{portal:this.portal},d.folders);d.items=b.resultsToTypedArray(l,{portal:this.portal,folderId:a},d.items);return d}))}});f={Portal:f([y],{declaredClass:"esri.arcgis.Portal",onLoad:function(){},constructor:function(a){c.mixin(this,{url:a});this.init(a).then(c.hitch(this,function(){this.emit("ready",this);this.onLoad(this)}))},init:function(a,d){a=(a||this.portalUrl).replace(/\/+$/,"");this.portalUrl=-1!==a.indexOf("/sharing")?a+"/":a+"/sharing/rest/";return this._getSelf(this.portalUrl).then(c.hitch(this,
function(a){e.self=c.mixin({},a);if(a=a.user)a.portal=this,a=new v(a),e.loggedInUser=c.mixin({},c.mixin(a,{credential:d}));e.self.id&&!1===e.self.canSearchPublic&&(e.extraQuery=" AND orgid:"+e.self.id);c.mixin(this,e.self);this.thumbnailUrl=b.formatUrl(this.portalUrl+"accounts/self/resources/"+this.thumbnail);this.isOrganization=this.access&&this.access.length||!1;this.created=this.created?new Date(this.created):null;this.modified=this.modified?new Date(this.modified):null;return this}))},signIn:function(){if(e&&
e.loggedInUser){var a=new m;a.resolve(e.loggedInUser);return a}e.options.disableIdentityLookup=!1;return t.id.getCredential(this.portalUrl).then(c.hitch(this,"init",this.url)).then(function(){return e.loggedInUser},function(a){e.options.disableIdentityLookup=!0;throw a;})},signOut:function(){e.loggedInUser.credential&&e.loggedInUser.credential.destroy();e.loggedInUser=null;e.options.disableIdentityLookup=!0;b.clearFieldsFromObject(e.self,this);e.self=null;return this.init(this.url)},getPortalUser:function(){return e.loggedInUser},
addResource:function(a,d){return b.request(this.portalUrl+"portals/self/addResource",{key:a,text:d},{usePost:!0})},update:function(a){return b.request(this.portalUrl+"portals/self/update",a,{usePost:!0})},queryGroups:function(a){return this._queryPortal(this.portalUrl+"community/groups",b.formatQueryParams({},a),s)},queryItems:function(a){return this._queryPortal(this.portalUrl+"search",b.formatQueryParams({},a),l)},queryListings:function(a){a=b.formatQueryParams({},a,!0);var d="";a.q&&-1<a.q.toLowerCase().indexOf("mylistings:true")?
(a.q=a.q.toLowerCase().replace("mylistings:true",""),d="?mylistings\x3dtrue"):a.q||(a.q='""');return this._queryPortal(this.portalUrl+"content/listings"+d,a,q)},getProvisions:function(){return this.getCustomers().then(c.hitch(this,function(a){return a.purchases}))},getInterests:function(){return this.getCustomers().then(c.hitch(this,function(a){return a.interests}))},getTrials:function(){return this.getCustomers().then(c.hitch(this,function(a){return a.trials}))},getCustomers:function(){return b.request(this.portalUrl+
"portals/self/customers")},getMyPurchases:function(){return this.getPurchases().then(function(a){return a.purchases})},getMyInterests:function(){return this.getPurchases().then(function(a){return a.interests})},getPurchases:function(){return b.request(this.portalUrl+"portals/self/purchases").then(c.hitch(this,function(a){a.interests=g.map(a.interests,function(a){return c.mixin(a.provision,{listing:a.listing})});a.purchases=g.map(a.purchases,function(a){return c.mixin(a.provision,{listing:a.listing})});
a.trials=g.map(a.trials,function(a){return c.mixin(a.provision,{listing:a.listing})});a.interests=b.resultsToTypedArray(r,{portal:this},a.interests);a.trials=b.resultsToTypedArray(r,{portal:this},a.trials);a.purchases=b.resultsToTypedArray(r,{portal:this},a.purchases);return a}))},queryUsers:function(a){return this._queryPortal(this.portalUrl+"community/users",b.formatQueryParams({sortField:"username"},a),v)},_getSelf:function(a){return b.request(a+"accounts/self?culture\x3d"+w.locale)},_queryPortal:function(a,
d,e){var f=c.mixin({num:10,start:0,sortField:"title",sortOrder:"asc"},d),g=["start","query","num","nextStart"];a=b.request(a,f).then(c.hitch(this,function(a){a.results=b.resultsToTypedArray(e,{portal:this},a);a.queryParams=c.mixin({},f);a.nextQueryParams=c.mixin(f,{start:a.nextStart});return b.clearFieldsFromObject(g,a)}));a=c.delegate(a);a.queryParams=c.mixin({},f);a.nextQueryParams=m.when(a,function(a){return a.nextQueryParams});return k(a)}}),PortalFolder:u,PortalGroup:s,PortalItem:l,PortalComment:n,
PortalRating:p,PortalUtil:b,PortalResult:k,PortalListing:q};x("extend-esri")&&c.mixin(c.getObject("arcgis",!0,t),f);return f});