/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/dijit/geoenrichment/Geoenrichment","../../declare dojo/_base/lang dojo/number dojo/on dojo/string dojo/promise/all ./bufferTitle esri/geometry/Polygon esri/units ./DataProvider ../../tasks/geoenrichment/GeoenrichmentTask ../../tasks/geoenrichment/EnrichParameters ../../tasks/geoenrichment/RingBuffer ../../tasks/geoenrichment/DriveBuffer ../../tasks/geoenrichment/GeographyLevel ../../tasks/geoenrichment/GeometryStudyArea ./config ./lang ./_Invoke dojo/json dojo/Deferred esri/tasks/locator".split(" "),
function(g,v,e,h,x,y,z,A,k,B,C,D,t,E,F,G,p,w,H,q,r,I){var u=g(null,{_keys:null,_values:null,_capacity:5,constructor:function(a){this._keys=[];this._values={};a&&(this._capacity=a)},getValue:function(a){return this._values[a]},setValue:function(a,b){this._keys.push(a);this._values[a]=b;this._removeOverflow()},hasValue:function(a){return this._values.hasOwnProperty(a)},_removeOverflow:function(){if(this._keys.length>this._capacity)for(var a=this._keys.splice(0,this._keys.length-this._capacity),b=0;b<
a.length;b++)delete this._values[a[b]]},setCapacity:function(a){this._capacity=a;this._removeOverflow()}});e=g(null,{_values:null,constructor:function(a){this._values=new u(a)},getValue:function(a){var b=new r,c=this.keyToString(a);if(this._values.hasValue(c))b.resolve(this._values.getValue(c));else{var f=this;this.keyToValue(a).then(function(a){f._values.setValue(c,a);b.resolve(a)},function(a){b.reject(a)})}return b.promise},keyToString:function(a){return q.stringify(a)},keyToValue:function(a){throw"Not implemented";
},setCapacity:function(a){this._values.setCapacity(a)}});var J=g([e],{keyToString:function(a){return q.stringify(a.toJson())},keyToValue:function(a){var b=new I(p.locatorUrl),c=new r;b.locationToAddress(a).then(function(a){c.resolve(x.substitute(p.addressFormat,a.address))},function(a){c.resolve("")});return c.promise}}),K=g([e],{_countryValues:null,_geometries:null,constructor:function(){this._countryValues=new u;this._geometries=new u(3)},keyToValue:function(a){var b=this,c=new C(p.server);c.token=
p.token;var f=q.stringify({highestLevel:a.highestLevel,variables:a.variables,country:a.country}),d=new D;d.forStorage=!1;d.countryID=a.country;d.datasetID=a.dataset;d.variables=a.variables;var l=q.stringify({inGeom:a.inGeom.toJson(),buffer:a.buffer}),s=this._buildPolygon(a),g=this._geometries.hasValue(l),n=a.returnGeometry&&!s&&!g;n&&(d.outSR=a.inGeom.spatialReference);n=new G({geometry:a.inGeom,options:a.buffer,returnGeometry:n});d.studyAreas.push(n);var e=[];if(a.levels)for(var m=0;m<a.levels.length;m++)e.push(a.levels[m]);
var h=this._countryValues.hasValue(f);a.highestLevel&&!h&&e.push(a.highestLevel);for(m=0;m<e.length;m++)n.comparisonGeographyLevels.push(new F({layerID:e[m]}));var k=new r;c.enrich(d).then(function(d){var c=d.featureSets[0].features;a.highestLevel&&(h?c.push(b._countryValues.getValue(f)):b._countryValues.setValue(f,c[c.length-1]));a.returnGeometry&&(g?c[0].geometry=b._geometries.getValue(l):s?(c[0].geometry=s,b._geometries.setValue(l,s)):b._geometries.setValue(l,c[0].geometry));k.resolve(d)},function(a){k.reject(a)});
return k.promise},setCapacity:function(a){this.inherited(arguments);this._countryValues.setCapacity(a)},_buildPolygon:function(a){switch(a.inGeom.type){case "point":if(!(a.buffer instanceof t))return null;break;case "polyline":return null;case "polygon":return a.inGeom}var b=a.buffer,c=new A(a.inGeom.spatialReference),f=[],d=b.radii[0];switch(b.units){case k.FEET:d*=0.3048;break;case k.MILES:d*=1609.344;break;case k.KILOMETERS:d*=1E3}for(b=0;80>b;b++){var l=2*(b/80)*Math.PI;f.push([a.inGeom.x+d*Math.cos(l),
a.inGeom.y+d*Math.sin(l)])}f.push(f[0]);c.addRing(f);return c}}),L=g([e],{metadata:null,_enrichCache:null,_addressCache:null,constructor:function(a){this._enrichCache=new K(a);this._addressCache=new J(3)},keyToValue:function(a){var b=this,c=[],f=a.returnAddress;delete a.returnAddress;c.push(this._enrichCache.getValue(a));f&&c.push(this._addressCache.getValue(a.inGeom));var d=new r;y(c).then(function(c){var g=c[0].featureSets[0],e=g.features[0];e.attributes[b.metadata.name]||(e.attributes[b.metadata.name]=
z(a.inGeom.type,a.buffer),f&&(e.attributes[b.metadata.address]=c[1]));d.resolve(g)},function(a){d.reject(a)});return d.promise},setCapacity:function(a){this.inherited(arguments);this._enrichCache.setCapacity(a)}});return g("esri.dijit.geoenrichment.Geoenrichment",[B,H],{country:null,dataset:null,returnGeometry:!1,returnAddress:!1,inGeom:null,buffer:null,variables:null,levels:null,highestLevel:null,data:null,restartOnDone:!1,requests:null,started:!1,cache:null,constructor:function(){this.buffer=new t;
this.cache=new L;this.cache.metadata=this.metadata},handleResponse:function(a){try{this.data=a,this.onDone(null)}catch(b){this.onDone(b)}},handleError:function(a){this.onDone(a)},onDone:function(a){this.requests=null;a?"CancelError"!=a.name&&(console.log(a),h.emit(this,"error",a)):h.emit(this,"data");this.restartOnDone?(this.invalidate(),this.restartOnDone=!1):(h.emit(this,"end"),this.started=!1)},requestData:function(){if(this.inGeom&&this.buffer&&this.variables){this.requests=[];this.started||(h.emit(this,
"start"),this.started=!0);var a,b;switch(this.inGeom.type){case "point":a=this.buffer;b=this.returnAddress;break;case "polyline":a=this.buffer instanceof E?new t:this.buffer;b=!1;break;case "polygon":a=null,b=!1}a=this.cache.getValue({country:this.country,dataset:this.dataset,variables:this.variables,returnGeometry:this.returnGeometry,inGeom:this.inGeom,buffer:a,levels:this.levels,highestLevel:this.highestLevel,returnAddress:b});this.requests.push(a);a.then(v.hitch(this,this.handleResponse),v.hitch(this,
this.handleError))}},invalidate:function(){this.pendingInvoke("requestData")||(this.requests?this.restartOnDone=!0:(this.geometry=null,this.invoke("requestData")))},setInGeom:function(a){this.inGeom=a;this.invalidate()},setBuffer:function(a){this.buffer=a;this.invalidate()},getBuffer:function(){return this.buffer},invalidateData:function(){this.data=null;this.invalidate()},setVariables:function(a){w.arraysEqual(this.variables,a)||(this.variables=a,this.invalidateData())},setGeoLevels:function(a,b){w.arraysEqual(this.levels,
a)&&this.highestLevel==b||(this.levels=a,this.highestLevel=b,this.invalidateData())},setCacheLimit:function(a){this.cache.setCapacity(a)},getData:function(){return this.data},getGeometry:function(){return this.data.features[0].geometry},isBusy:function(){return this.pendingInvoke("requestData")||this.requests||this.restartOnDone},stop:function(){this.restartOnDone=!1;this.cancelInvoke("requestData");if(this.requests)for(var a=this.requests.slice(0),b=0;b<a.length;b++)a[b].cancel()},setReturnAddress:function(a){this.returnAddress!=
a&&(this.returnAddress=a)&&this.invalidateData()}})});