/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
require({cache:{"url:esri/dijit/geoenrichment/templates/InfographicsCarousel.html":'\ufeff\x3cdiv style\x3d"display: inline-block;"\x3e\r\n    \x3ctable class\x3d"Browser_Table" cellpadding\x3d"0" cellspacing\x3d"0"\x3e\r\n        \x3ctr\x3e\r\n            \x3ctd class\x3d"Browser_BackTd"\x3e\r\n                \x3cdiv class\x3d"Browser_Back" data-dojo-attach-event\x3d"click: _slideBack"\x3e\x3c/div\x3e\r\n            \x3c/td\x3e\r\n            \x3ctd align\x3d"center"\x3e\r\n                \x3cdiv data-dojo-attach-point\x3d"_container" class\x3d"Browser_HostBorder"\x3e\r\n                    \x3cdiv data-dojo-attach-point\x3d"_titlePane" class\x3d"Browser_TitlePane" style\x3d"visibility: hidden;"\x3e\r\n                        \x3cselect data-dojo-type\x3d"dijit/form/Select"\r\n                            data-dojo-attach-point\x3d"_select"\r\n                            data-dojo-attach-event\x3d"onChange: _onSelectChange"\x3e\r\n                        \x3c/select\x3e\r\n                    \x3c/div\x3e\r\n                    \x3cdiv class\x3d"Browser_ContentPane"\x3e\r\n                        \x3cdiv data-dojo-type\x3d"esri/dijit/geoenrichment/Infographic"\r\n                            data-dojo-attach-point\x3d"_infographic"\r\n                            data-dojo-props\x3d"autoWidth: false, autoHeight: false, title: \'\'"\r\n                            data-dojo-attach-event\x3d"onDataRequest: _showProgress, onDataLoad: _onDataLoad, onDataReady: _onDataReady, onDataError: _onDataError"\r\n                            style\x3d"position: absolute; width: 100%; height: 100%; top: 0; left: 0;"\x3e\r\n                        \x3c/div\x3e\r\n                    \x3c/div\x3e\r\n                \x3c/div\x3e\r\n                \x3cdiv data-dojo-attach-point\x3d"_updateProgress" class\x3d"Browser_UpdateProgress" style\x3d"display: none;"\x3e\x3c/div\x3e\r\n            \x3c/td\x3e\r\n            \x3ctd class\x3d"Browser_ForwardTd"\x3e\r\n                \x3cdiv class\x3d"Browser_Forward" data-dojo-attach-event\x3d"click: _slideForward"\x3e\x3c/div\x3e\r\n            \x3c/td\x3e\r\n        \x3c/tr\x3e\r\n    \x3c/table\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_reloadProgress"\x3e\r\n        \x3cdiv class\x3d"Browser_ReloadProgressBack"\x3e\x3c/div\x3e\r\n        \x3cdiv class\x3d"Browser_ReloadProgress"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/dijit/geoenrichment/InfographicsCarousel","../../declare dojo/_base/fx dojo/_base/lang dojo/aspect dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/fx dojo/has dojox/gesture/swipe dojox/mvc/Templated dojo/text!./templates/InfographicsCarousel.html ./dom ./Infographic dojo/on dojo/dom-class ./InfographicsOptions ./_Interop ./bufferTitle ./theme ../../tasks/geoenrichment/GeoenrichmentTask ../../tasks/geoenrichment/GeometryStudyArea ../../tasks/geoenrichment/studyAreaFromJson ./config esri/dijit/_EventedWidget ./UserError dijit/layout/BorderContainer dijit/layout/ContentPane dijit/form/Select".split(" "),
function(g,w,d,n,x,y,f,p,z,c,A,B,K,L,q,r,s,k,M,C,D,t,E,u,F,G){function H(a,b,e){function d(a,b,c,h,g){var f={};f[b]={start:c,end:h};g&&(f[b].units=g);return w.animateProperty({node:a,properties:f,duration:e})}if(b&&e){var h=a.cloneNode(!0);a.parentNode.insertBefore(h,a);var c;if(!y.isBodyLtr())switch(b){case l:b=m;break;case m:b=l}switch(b){case v:c=p.combine([d(h,"opacity",1,0),d(a,"opacity",0,1)]);break;case l:c=p.combine([d(h,"left",0,-100,"%"),d(a,"left",100,0,"%")]);break;case m:c=p.combine([d(h,
"left",0,100,"%"),d(a,"left",-100,0,"%")])}n.after(c,"onEnd",function(){x.destroy(h)});c.play()}}var v="f",l="sf",m="sb",I=g(c.Swipe,{_process:function(a,b,e){e._locking=e._locking||{};!e._locking[this.defaultEvent]&&!this.isLocked(e.currentTarget)&&(e._locking[this.defaultEvent]=!0,this[b](a.data,e))}}),J=g([],{_swipe:null,_node:null,_rtl:null,_ltr:null,_distance:50,constructor:function(a,b,e,c){this._node=a;this._rtl=b;this._ltr=e;c&&(this._distance=c);this._swipe=new I;q(this._node,this._swipe,
function(){});q(this._node,this._swipe.end,d.hitch(this,"_end"))},_end:function(a){a=a.dx;Math.abs(a)<this._distance||(0>a&&this._rtl?this._rtl():this._ltr&&this._ltr())}});c=g("esri.dijit.geoenrichment.InfographicsCarousel",[A,F],{templateString:B,studyArea:null,studyAreaTitle:null,selectedIndex:0,options:null,expanded:!0,returnGeometry:!1,animDuration:200,_items:null,_loading:null,_infographic:null,_getCountryPromise:null,_countryForStudyArea:!1,_pendingAnimation:null,_pendingReload:!0,_eventMap:{resize:["size"],
"data-ready":["provider"],"data-error":["error"]},postCreate:function(){this.inherited(arguments);setTimeout(d.hitch(this,this._onResize),0);z("touch")&&new J(this._container,d.hitch(this,"_slideForward"),d.hitch(this,"_slideBack"))},startup:function(){this.inherited(arguments);this.options||this.set("options",new s)},_setReturnGeometryAttr:function(a){this._set("returnGeometry",a);this._infographic.set("returnGeometry",a)},_setStudyAreaAttr:function(a){if(!(a instanceof t))throw Error("Not implemented yet");
this._countryForStudyArea=!1;this._set("studyArea",a);this._getCountryPromise||(this._infographic.get("countryID")?this._infographic.set("studyArea",a):this._getCountry());this._updateSubtitle()},_getCountry:function(){if(!this._getCountryPromise){var a=new D(u.server);a.token=u.token;var b=this.get("studyArea");this._getCountryPromise=a.getCountries(b.geometry);this._getCountryPromise.always(d.hitch(this,function(){this._getCountryPromise=null}));this._getCountryPromise.then(d.hitch(this,this._onGetCountryComplete,
b),d.hitch(this,this._onDataError))}},_onGetCountryComplete:function(a,b){0==b.length?this._onDataError(new G("There is no data for the selected area")):(this.studyArea===a&&(this._countryForStudyArea=!0),this._infographic.set("countryID",b[0]),this._infographic.set("studyArea",this.studyArea),this._getReports())},_setStudyAreaTitleAttr:function(a){this._set("studyAreaTitle",a);this._updateSubtitle()},_updateSubtitle:function(){this._infographic.set("subtitle",this.studyArea instanceof t?"polygon"==
this.studyArea.geometry.type?this.studyAreaTitle?this.studyAreaTitle:"${name}":this.studyAreaTitle?"\x3cdiv\x3e${address}\x3c/div\x3e\x3cdiv\x3e"+this.studyAreaTitle+" (${name})\x3c/div\x3e":"\x3cdiv\x3e${address}\x3c/div\x3e\x3cdiv\x3e${name}\x3c/div\x3e":"\x3cdiv\x3e${address}\x3c/div\x3e\x3cdiv\x3e${name}\x3c/div\x3e")},_setOptionsAttr:function(a){this._set("options",a);this._getReports();this._infographic.set("studyAreaOptions",a.studyAreaOptions);C.set(this.domNode,this.options.theme)},_getReports:function(){if(this.options){var a=
this._infographic.get("countryID");a&&this.options.getItems(a).then(d.hitch(this,this._fillReports),d.hitch(this,this._onDataError))}},_fillReports:function(a){this._items=[];this._select.removeOption(this._select.getOptions());for(var b=0;b<a.length;b++)if(a[b].isVisible){var e=a[b];this._items.push(e);this._select.addOption({value:(this._items.length-1).toString(),label:e.title})}this._infographic.set("cacheLimit",this._items.length);this._titlePane.style.visibility="";this._updateSelection()},
_setExpandedAttr:function(a){this._set("expanded",a);a?r.remove(this.domNode,"Collapsed"):r.add(this.domNode,"Collapsed");this._infographic.set("expanded",a);this._pendingReload=!0},_setSelectedIndexAttr:function(a){this.selectedIndex!=a&&(this._set("selectedIndex",a),this._updateSelection())},_updateSelection:function(){if(this._items){this._pendingAnimation||(this._pendingAnimation=v);this._pendingReload=!0;var a=this._items[this.selectedIndex];this._select.set("value",this.selectedIndex);this._infographic.set("type",
a.type);this._infographic.set("variables",a.variables);this._infographic.set("datasetID",a.datasetID)}},_onDataReady:function(a){var b=!1,e=a.getData();if(0<e.features.length)for(var d=e.features[0],c=0;c<e.fields.length;c++)if(e.fields[c].fullName&&d.attributes[e.fields[c].name]){b=!0;break}b?(H(this._infographic.domNode,this._pendingAnimation,this.animDuration),this._pendingAnimation=null,this.onDataReady(a)):this._countryForStudyArea||(this._infographic.set("variables",null),a.stop(),this._getCountry())},
onDataReady:function(a){},_onDataLoad:function(){this._getCountryPromise||(this._hideProgress(),this.onDataLoad())},onDataLoad:function(){},_onDataError:function(a){console.error(a);this._hideProgress();this.onDataError(a)},onDataError:function(a){},_showProgress:function(){this._pendingReload?(f.set(this._reloadProgress,"display",""),this._pendingReload=!1):f.set(this._updateProgress,"display","")},_hideProgress:function(){f.set(this._reloadProgress,"display","none");f.set(this._updateProgress,"display",
"none")},_slideBack:function(){this._pendingAnimation=m;this._infographic.set("effect","slideBack");var a=this.get("selectedIndex")-1;0>a&&(a=this._items.length-1);this.set("selectedIndex",a)},_slideForward:function(){this._pendingAnimation=l;var a=this.get("selectedIndex")+1;a>=this._items.length&&(a=0);this.set("selectedIndex",a)},_onSelectChange:function(){this.set("selectedIndex",+this._select.get("value"))},_onResize:function(){this.onResize([this.domNode.scrollWidth,this.domNode.scrollHeight])},
onResize:function(a){}});c.Interop=g([c,k],{postMixInProperties:function(){n.after(this,"onResize",d.hitch(this,function(a){this._onCommand("OnResize",a[0],a[1])}),!0);n.after(this,"onDataError",d.hitch(this,this._onCommand,"OnDataError"),!0);this.inherited(arguments)},converters:{studyArea:new k.JsonConverter(E),options:new k.CtorConverter(s),expanded:k.BoolConverter},setValue:function(a,b){"inGeom"==a&&(arguments[0]="studyArea",arguments[1]={geometry:b});this.inherited(arguments)}});return c});