/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/layers/GraphicsLayer","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/dom-attr dojo/dom-construct dojo/dom-style dojox/gfx dojox/gfx/matrix esri/kernel esri/lang esri/sniff esri/domUtils esri/layers/layer esri/symbols/MarkerSymbol esri/symbols/SimpleMarkerSymbol esri/geometry/Point esri/geometry/ScreenPoint esri/geometry/Extent esri/geometry/mathUtils esri/geometry/screenUtils".split(" "),function(w,v,r,m,I,M,G,A,u,J,Q,E,F,U,V,x,R,K,B,S,L){var H,N=-1!==A.renderer.toLowerCase().indexOf("svg"),
O=-1!==A.renderer.toLowerCase().indexOf("canvas"),t=9>E("ie"),T=w(null,{declaredClass:"esri.layers._GraphicsContainer",_setMap:function(a,b){var c,d=this._connects=[];this._map=a;O?(c=M.create("div",{style:"overflow: visible; position: absolute;"},b),this._surface={getEventSource:function(){return c}},d.push(v.connect(c,"onmousedown",this,this._canvasDownHandler)),d.push(v.connect(c,"onmouseup",this,this._canvasUpHandler)),d.push(v.connect(c,"onclick",this,this._canvasClickHandler)),H.prototype._canvas=
!0):(c=(this._surface=A.createSurface(b,a.width,a.height)).getEventSource(),G.set(c=t?c.parentNode:c,{overflow:"visible",position:"absolute"}));d.push(v.connect(a,"onResize",this,"_onResizeHandler"));return c},_onResizeHandler:function(a,b,c){a=this._surface.getEventSource();var d=this._map,e;t&&G.set(a=a.parentNode,{width:b+"px",height:c+"px",clip:"rect(0px "+b+"px "+c+"px 0px)"});I.set(a,"width",b);I.set(a,"height",c);this._surface.declaredClass||m.forEach(a.childNodes,function(a){I.set(a,"width",
b);I.set(a,"height",c)});d.loaded&&(d.graphics.suspended||(d.graphics._resized=!0),m.forEach(d.graphicsLayerIds,function(a){e=d.getLayer(a);e.suspended||(e._resized=!0)}))},_cleanUp:function(){m.forEach(this._connects,v.disconnect,v);this._map=this._surface=null},_processEvent:function(a){var b=this._map;a.screenPoint=new K(a.pageX-b.position.x,a.pageY-b.position.y);a.mapPoint=b.toMap(a.screenPoint)},_canvasDownHandler:function(a){this._processEvent(a);this._downPt=a.screenPoint.x+","+a.screenPoint.y},
_canvasUpHandler:function(a){this._processEvent(a);this._upPt=a.screenPoint.x+","+a.screenPoint.y},_tolerance:15,_canvasClickHandler:function(a){if(this._downPt&&this._upPt&&this._downPt===this._upPt){this._processEvent(a);var b=this._map,c=m.map(b.graphicsLayerIds,function(a){return b.getLayer(a)});c.push(b.graphics);c.reverse();var c=m.filter(c,function(a){return a.loaded&&a._mouseEvents&&!a.suspended&&(!Q.isDefined(a.opacity)||0<a.opacity)}),d=a.screenPoint,e=this._tolerance,f=d.x-e,g=d.y+e,h=
d.x+e,e=d.y-e,k=new B(f,e,h,g),f=b.toMap(new K(f,g)),h=b.toMap(new K(h,e)),g=f.spatialReference._getInfo(),l=new B(B.prototype._normalizeX(f.x,g).x,f.y,B.prototype._normalizeX(h.x,g).x,h.y,f.spatialReference),n,p=E("esri-touch");delete k.spatialReference;m.some(c,function(a){a=m.filter(a.graphics,function(a){var c=a.getDojoShape();if(!a.visible||!c)return!1;var b=c.getTransformedBoundingBox();return b?(a=new B(b[0].x,b[0].y,b[2].x,b[2].y),delete a.spatialReference,p?a.intersects(k):a.contains(d)):
m.some(c.children||[],function(a){b=a.getTransformedBoundingBox();a=new B(b[0].x,b[0].y,b[2].x,b[2].y);delete a.spatialReference;return p?a.intersects(k):a.contains(d)})});a.reverse();if(0<a.length){var c;m.some(a,function(a){return a.geometry&&l.intersects(a.geometry)?(c=a,!0):!1});if(c)return n=c,!0}return!1});if(n&&(c=n.getLayer()))a.graphic=n,c.onClick(a)}}});H=w(U,{declaredClass:"esri.layers._GraphicsLayer",managedSuspension:!0,surfaceType:O?"canvas-2d":A.renderer,_eventMap:{"graphic-add":["graphic"],
"graphic-remove":["graphic"]},constructor:function(a,b){if(a&&(r.isString(a)||r.isObject(a)&&a.layerDefinition))a=b;this._params=r.mixin({displayOnPan:!0,drawMode:!0,styling:!0},a||{});var c=this._params.dataAttributes;"string"===typeof c&&(c=[c]);this.styling=N?this._params.styling:!0;this.dataAttributes=c;this.infoTemplate=a&&a.infoTemplate;this.graphics=[];this._draw=r.hitch(this,this._draw);this._refresh=r.hitch(this,this._refresh);this.registerConnectEvents()},getNode:function(){return this._div&&
this._div.getEventSource()},setDrawMode:function(a){this._params.drawMode=a},renderer:null,_setMap:function(a,b){this.inherited(arguments);this._map=a;this._wrap=a.wrapAround180;this._srInfo=a.spatialReference._getInfo();this._canvas?(b=A.createSurface(b.getEventSource(),a.width,a.height),G.set(b.rawNode,"position","absolute"),this._div=b.createGroup(),this._renderProto=this._div.constructor.prototype._render,this._div._render=r.hitch(this,this._canvasRender)):this._div=b.createGroup();this._div.getEventSource().id=
this.id+"_layer";var c=this.opacity;Q.isDefined(c)&&1>c&&this.setOpacity(c,!0);return this._div},_unsetMap:function(a,b){m.forEach(this.graphics,function(a){a._shape=null});this._canvas?(b=this._div.getParent(),b._parent={},M.destroy(b.rawNode),b.destroy()):(this._div.clear(),b.remove(this._div),M.destroy(this._div.getEventSource()));this._map=this._div=null;clearTimeout(this._wakeTimer);this._wakeTimer=null;this._disableDrawConnectors();this.inherited(arguments)},_onZoomStartHandler:function(){F.hide(this._div.getEventSource())},
_onExtentChangeHandler:function(a,b,c,d){clearTimeout(this._wakeTimer);this._wakeTimer=null;c?(a=this._map.__visibleRect,b=this._div,this._evalSDRenderer(),this._refresh(!0),b.setTransform(u.translate({x:a.x,y:a.y})),this._renderProto&&b.surface.pendingRender?this._dirty=!0:this.suspended||F.show(b.getEventSource())):this._resized&&(this._refresh(!1),this._resized=!1);if(0<this.graphics.length)this.onUpdate()},_canvasRender:function(){var a=this._div;this._dirty&&(delete this._dirty,this.suspended||
F.show(a.getEventSource()));return this._renderProto.apply(a,arguments)},_refresh:function(a){var b=this.graphics,c=b.length,d,e=this._draw;for(d=0;d<c;d++)e(b[d],a)},refresh:function(){this._refresh(!0)},redraw:function(){this._refresh(!0)},_onPanHandler:function(a,b){this._panDx=b.x;this._panDy=b.y;var c=this._map.__visibleRect;this._div.setTransform(u.translate({x:c.x+b.x,y:c.y+b.y}))},_onPanEndUpdateHandler:function(a,b){if(!this._params._child&&(b.x!==this._panDx||b.y!==this._panDy)){var c=this._map.__visibleRect;
this._div.setTransform(u.translate({x:c.x,y:c.y}))}this._refresh(!1);if(this.graphics.length)this.onUpdate()},_onPanStartHandler:function(){F.hide(this._div.getEventSource())},_onPanEndHandler:function(){var a=this._map.__visibleRect,b=this._div;b.setTransform(u.translate({x:a.x,y:a.y}));this._refresh(!1);this._renderProto&&b.surface.pendingRender?this._dirty=!0:F.show(b.getEventSource());if(this.graphics.length)this.onUpdate()},onSuspend:function(){this.inherited(arguments);F.hide(this._div.getEventSource());
clearTimeout(this._wakeTimer);this._wakeTimer=null;this._disableDrawConnectors()},onResume:function(a){this.inherited(arguments);a.firstOccurrence&&this._evalSDRenderer();this._enableDrawConnectors();this._wakeTimer=this._wakeTimer||setTimeout(r.hitch(this,function(){this.suspended||this._onExtentChangeHandler(null,null,!0)}),0)},_enableDrawConnectors:function(){var a=this._map,b=v.connect;this._disableDrawConnectors();this._params.displayOnPan?(this._params._child||(this._onPanHandler_connect=b(a,
"onPan",this,"_onPanHandler")),this._onPanEndHandler_connect=b(a,"onPanEnd",this,"_onPanEndUpdateHandler")):(this._onPanStartHandler_connect=b(a,"onPanStart",this,"_onPanStartHandler"),this._onPanEndHandler_connect=b(a,"onPanEnd",this,"_onPanEndHandler"));this._onZoomStartHandler_connect=b(a,"onZoomStart",this,"_onZoomStartHandler");this._onExtentChangeHandler_connect=b(a,"onExtentChange",this,"_onExtentChangeHandler")},_disableDrawConnectors:function(){var a=v.disconnect;a(this._onExtentChangeHandler_connect);
a(this._onZoomStartHandler_connect);a(this._onPanHandler_connect);a(this._onPanStartHandler_connect);a(this._onPanEndHandler_connect);this._onExtentChangeHandler_connect=this._onZoomStartHandler_connect=this._onPanHandler_connect=this._onPanStartHandler_connect=this._onPanEndHandler_connect=null},_updateExtent:function(a){var b=a.geometry;if(b){if(!(a._extent=b.getExtent())){var c,d;if("esri.geometry.Point"===b.declaredClass)c=b.x,d=b.y;else if("esri.geometry.Multipoint"===b.declaredClass)c=b.points[0][0],
d=b.points[0][1];else{a._extent=null;return}a._extent=new B(c,d,c,d,b.spatialReference)}}else a._extent=null},_intersects:function(a,b,c){var d=a.spatialReference,e=b.spatialReference,f=d&&e&&!d.equals(e)&&d._canProject(e)&&4326===e.wkid;if(this._wrap&&!c){c=[];var d=a._getFrameWidth(),g=this._srInfo,h=a._clip?a._getAvailExtent():a.extent,k,l,n,p,P=[];k=b._partwise;f&&(h=a.geographicExtent,g=e._getInfo());a=h._getParts(g);if(k&&k.length){b=[];e=0;for(f=k.length;e<f;e++)b=b.concat(k[e]._getParts(g))}else b=
b._getParts(g);e=0;for(f=b.length;e<f;e++){n=b[e];g=0;for(h=a.length;g<h;g++)if(p=a[g],p.extent.intersects(n.extent)){k=0;for(l=n.frameIds.length;k<l;k++)c.push((p.frameIds[0]-n.frameIds[k])*d)}}e=0;for(f=c.length;e<f;e++)k=c[e],m.indexOf(c,k)===e&&P.push(k);return P.length?P:null}return(f?a.geographicExtent:a.extent).intersects(b)?[0]:null},_defaultMarker:{type:"simplemarkersymbol",style:"square",size:1,xoffset:0,yoffset:0,angle:0},_draw:function(a,b){if(this._params.drawMode&&this._map&&!this.suspended)try{var c=
a._extent,d,e,f=!N||this.styling,g=N&&this.dataAttributes,h=a.getDojoShape(),k;if(a.visible&&c&&(d=this._intersects(this._map,c,a.geometry._originOnly))&&(e=f?this._getSymbol(a):this._defaultMarker)){if(!a._offsets||a._offsets.join(",")!==d.join(",")?a._offsets=d:k=!0,!h||b||!k){var l=a.geometry.type,c={graphic:a},n,p,m=f&&!a.symbol?this._getRenderer(a):null,z=m&&m.backgroundFillSymbol;if("point"===l)this._isInvalidShape(e,h)&&this._removeShape(a),a._shape=this._drawPoint(this._div,a.geometry,e,a.getDojoShape(),
d,m,a),f&&this._symbolizePoint(a.getDojoShape(),e);else if("multipoint"===l)this._drawMarkers(a,e,d,m),f&&this._symbolizeMarkers(a,e);else{var D,l=e,C=h&&h.children&&h;f&&(l=(D=e.isInstanceOf(V)?e:null)?z:e);if(l&&D)C||(h&&this._removeShape(a),C=a._shape=this._div.createGroup());else if(l||D)if(C||this._isInvalidShape(l||D,h))this._removeShape(a),C=null;l&&(h=this._drawShape(a,d,C),this._symbolizeShape(h,l,!z&&m,a));D&&(h=this._drawPoint(C||this._div,a.geometry.getCentroid(),D,C?C.children[1]:a._shape,
d,m,a),this._symbolizePoint(h,D));C||(a._shape=h)}p=a.getDojoShape();if(c.node=n=p&&p.getNode())if(n.e_graphic=a,this._addDataAttrs(a,g,n),p!==h)this.onGraphicNodeAdd(c);this.onGraphicDraw(c)}}else h&&this._removeShape(a)}catch(W){this._errorHandler(W,a)}},_removeShape:function(a){var b=a.getDojoShape(),c=b.getNode();b.removeShape();b.destroy();a._shape=a._offsets=null;c&&(c.e_graphic=null,this.onGraphicNodeRemove({graphic:a,node:c}))},_addDataAttrs:function(a,b,c){var d=a.attributes,e,f=b?b.length:
0,g=this._getRenderer(a);if(c&&d){for(e=0;e<f;e++)(c=b[e])&&a.attr("data-"+c,d[c]);!this.styling&&g&&(g.getBreakIndex?(b=g.getBreakIndex(a),a.attr("data-class-break",-1!==b?b:null)):g.getUniqueValueInfo&&(b=g.getUniqueValueInfo(a),a.attr("data-unique-value",b?b.value:null)))}},_drawShape:function(a,b,c){var d=a.geometry;a=c?c.children[0]:a.getDojoShape();c=c||this._div;var e=d.type,f=this._map,g=f.extent,h=f.width,k=f.height,f=f.__visibleRect,l=[],n,p;n="extent"===e;if("rect"===e||n)l={x:0,y:0,spatialReference:d.spatialReference},
l.x=n?d.xmin:d.x,l.y=n?d.ymax:d.y,e=L.toScreenPoint(g,h,k,l),l.x=n?d.xmax:d.x+d.width,l.y=n?d.ymin:d.y+d.height,d=L.toScreenPoint(g,h,k,l),b={x:e.x-f.x+b[0],y:e.y-f.y,width:Math.abs(d.x-e.x),height:Math.abs(d.y-e.y)},0===b.width&&(b.width=1),0===b.height&&(b.height=1),a=this._drawRect(c,a,b);else if("polyline"===e||"polygon"===e){n=0;for(p=b.length;n<p;n++)l=l.concat(L._toScreenPath(g,h,k,d,-f.x+b[n],-f.y));a=this._drawPath(c,a,l);this._rendererLimits&&("polyline"===e?this._clipPolyline(a,d):this._clipPolygon(a,
d))}return a},_drawRect:function(a,b,c){return b?b.setShape(c):a.createRect(c)},_drawImage:function(a,b,c){return b?b.setShape(c):a.createImage(c)},_drawCircle:function(a,b,c){return b?b.setShape(c):a.createCircle(c)},_drawPath:function(){return t?function(a,b,c,d){c=d?c:c.join(" ");if(b)return b.setShape(c);b=a.createObject(d?A.Path:A.EsriPath,c);a._overrideSize(b.getEventSource());return b}:function(a,b,c,d){c=d?c:c.join(" ");return b?b.setShape(c):a.createPath(c)}}(),_drawText:function(a,b,c){return b?
b.setShape(c):a.createText(c)},_evalSDRenderer:function(){var a=this._map,b=this.renderer,c;a&&(a.loaded&&b&&b.getRendererInfo)&&(c="zoom"===b.rangeType?b.getRendererInfoByZoom(a.getZoom()):b.getRendererInfoByScale(a.getScale()));this._rndForScale=c&&c.renderer},_getRenderer:function(a){var b=this._rndForScale||this.renderer;a&&(b&&b.getObservationRenderer)&&(b=b.getObservationRenderer(a));return b},_getSymbol:function(a){var b=this._getRenderer();return a.symbol||b&&b.getSymbol(a)},_symbolizeShape:function(a,
b,c,d){var e=b._stroke,f=b._fill;c=c&&c.proportionalSymbolInfo?c.getSize(d):null;if(null===e||null===f)e=b.getStroke(),f=b.getFill();a.setStroke(null==c?e:r.mixin({},e,{width:c})).setFill(f);b._stroke=e;b._fill=f},_smsToPath:function(){return t?function(a,b,c,d,e,f,g,h,k){switch(b){case a.STYLE_SQUARE:return["M",e+","+g,"L",f+","+g,f+","+h,e+","+h,"X","E"];case a.STYLE_CROSS:return["M",c+","+g,"L",c+","+h,"M",e+","+d,"L",f+","+d,"E"];case a.STYLE_X:return["M",e+","+g,"L",f+","+h,"M",e+","+h,"L",f+
","+g,"E"];case a.STYLE_DIAMOND:return["M",c+","+g,"L",f+","+d,c+","+h,e+","+d,"X","E"];case a.STYLE_TARGET:return["M",e+","+g,"L",f+","+g,f+","+h,e+","+h,e+","+g,"M",e-k+","+d,"L",e+","+d,"M",c+","+(g-k),"L",c+","+g,"M",f+k+","+d,"L",f+","+d,"M",c+","+(h+k),"L",c+","+h,"E"]}}:function(a,b,c,d,e,f,g,h,k){switch(b){case a.STYLE_SQUARE:return["M",e+","+g,f+","+g,f+","+h,e+","+h,"Z"];case a.STYLE_CROSS:return["M",c+","+g,c+","+h,"M",e+","+d,f+","+d];case a.STYLE_X:return["M",e+","+g,f+","+h,"M",e+","+
h,f+","+g];case a.STYLE_DIAMOND:return["M",c+","+g,f+","+d,c+","+h,e+","+d,"Z"];case a.STYLE_TARGET:return["M",e+","+g,f+","+g,f+","+h,e+","+h,e+","+g,"M",e-k+","+d,e+","+d,"M",c+","+(g-k),c+","+g,"M",f+k+","+d,f+","+d,"M",c+","+(h+k),c+","+h]}}}(),_pathStyles:{square:1,cross:1,x:1,diamond:1,target:1},_typeMaps:{picturemarkersymbol:"image",picturefillsymbol:"path",simplefillsymbol:"path",textsymbol:"text"},_isInvalidShape:function(a,b){var c=b&&b.shape&&b.shape.type,d=a&&a.type,e=a&&a.style;d&&(e=
this._typeMaps[d]||e);this._pathStyles[e]&&(e="path");if(c&&e&&c!==e)return!0},_drawPoint:function(a,b,c,d,e,f,g){var h=c.type,k=this._map,l=k.__visibleRect,n=L.toScreenPoint(k.extent,k.width,k.height,b).offset(-l.x+e[0],-l.y),k=n.x,l=n.y,p;b=[];var m=f&&f.rotationInfo?f.getRotationAngle(g):null,z=f&&f.proportionalSymbolInfo;f=z?f.getSize(g,{shape:c.style}):null;m&&b.push(u.rotategAt(m,n));(0!==c.xoffset||0!==c.yoffset)&&b.push(u.translate(c.xoffset,-c.yoffset));0!==c.angle&&b.push(u.rotategAt(c.angle,
n));if("simplemarkersymbol"===h)switch(p=c.style,h=Math.round,f=z?f:c.size,p){case x.STYLE_SQUARE:case x.STYLE_CROSS:case x.STYLE_X:case x.STYLE_DIAMOND:c=isNaN(f)?16:f/2;p=this._drawPath(a,d,this._smsToPath(x,p,k,l,h(k-c),h(k+c),h(l-c),h(l+c)));break;case x.STYLE_TARGET:n=c._targetWidth/2;f=c._targetHeight/2;p=this._drawPath(a,d,this._smsToPath(x,p,k,l,h(k-n),h(k+n),h(l-f),h(l+f),c._spikeSize));break;case x.STYLE_PATH:p=this._drawPath(a,d,c.path,!0);a=p.getBoundingBox();c=-(a.x+a.width/2)+k;k=-(a.y+
a.height/2)+l;l=a.width/a.height;h=d=1;isNaN(f)||(1<l?(d=f/a.width,h=f/l/a.height):(h=f/a.height,d=f*l/a.width),(1!==d||1!==h)&&b.push(u.scaleAt(d,h,n)));b.push(u.translate(c,k));break;default:c=isNaN(f)?16:f/2,p=this._drawCircle(a,d,{cx:k,cy:l,r:c})}else"shieldlabelsymbol"===h?(p=c.width,n=c.height,d=a.createGroup(),p=a.createImage({x:k-p/2,y:l-n/2,width:p,height:n,src:c.url}),d.add(p),null!=c.font&&(l+=0.2*c.getHeight(),a=a.createText({type:"text",text:c.text,x:k,y:l,align:"middle",decoration:c.decoration,
rotated:c.rotated,kerning:c.kerning}),a.setFont(c.font),a.setFill(c.color),d.add(a)),p=d):"picturemarkersymbol"===h?(p=z?f:c.width,n=z?f:c.height,p=this._drawImage(a,d,{x:k-p/2,y:l-n/2,width:p,height:n,src:c.url})):"textsymbol"===h&&(p=this._drawText(a,d,{type:"text",text:c.text,x:k,y:l,align:c.align,decoration:c.decoration,rotated:c.rotated,kerning:c.kerning}));p.setTransform(u.multiply(b));p._wrapOffsets=e;return p},_symbolizePoint:function(a,b){var c=b.type;if("shieldlabelsymbol"!==c&&"picturemarkersymbol"!==
c){var d=b._stroke,e=b._fill;if("textsymbol"===c)a.setFont(b.font).setFill(b.getFill());else{if(null===d||null===e)d=b.getStroke(),e=b.getFill();"simplemarkersymbol"===c&&a.setFill(e).setStroke(d);b._stroke=d;b._fill=e}}},_drawMarkers:function(a,b,c,d){var e=a.geometry,f=e.points,g=a.getDojoShape()||this._div.createGroup(),h,k,l=f.length,n=[],p=0,m,z=c?c.length:0;g.children[0]&&this._isInvalidShape(b,g.children[0])&&g.clear();for(k=0;k<l;k++){h=f[k];for(m=0;m<z;m++)n[0]=c[m],this._drawPoint(g,{x:h[0],
y:h[1],spatialReference:e.spatialReference},b,g.children[p++],n,d,a)}b=g.children.length;if(l*c.length<b)for(k=b-1;k>=l*c.length;k--)g.children[k].removeShape();a._shape=g},_symbolizeMarkers:function(a,b){var c=a.getDojoShape().children,d,e=c.length;for(d=0;d<e;d++)this._symbolizePoint(c[d],b)},_errorHandler:function(a,b){a.message=b?"Unable to draw graphic (geometry:"+(b.geometry?b.geometry.declaredClass:null)+", symbol:"+(b.symbol?b.symbol.declaredClass:null)+"): "+a.message:"Unable to draw graphic (null): "+
a.message;this.inherited(arguments)},_rendererLimits:function(){var a,b,c;E("ff")?(a=16125,b=-32250,c=32250):t?(a=1E5,b=-1E5,c=1E5):E("chrome")&&6>E("chrome")&&(a=8150,b=-1E4,c=1E4);if(a)return{clipLimit:a,rangeMin:b,rangeMax:c,clipBBox:[-a,-a,a,a],clipSegments:[[[-a,-a],[a,-a]],[[a,-a],[a,a]],[[a,a],[-a,a]],[[-a,a],[-a,-a]]]}}(),_clipPolyline:function(a,b){var c=this._getCorners(a,b),d=c.br,e=this._rendererLimits,f=e.rangeMin,g=e.rangeMax,h=e.clipBBox,k=e.clipSegments,e=this._isPointWithinRange,
l=this._isPointWithinBBox,n=this._getClipperIntersection,p=this._getPlaneIndex;if(!e(c.tl,f,g)||!e(d,f,g)){t&&this._createSegments(a);var r=[];m.forEach(a.segments,function(a){a=a.args;var c=a.length,b=[],d;for(d=0;d<c;d+=2){var e=[a[d],a[d+1]],f=[a[d+2],a[d+3]],g=l(e,h),m=l(f,h);if(g^m){if(m=n([e,f],k))g?(d?b.push(m[1]):b.push(e,m[1]),r.push(b),b=[]):b.push(m[1],f)}else g?d?b.push(f):b.push(e,f):(m=p(e,h),g=p(f,h),-1===m||(-1===g||m===g)||(e=n([e,f],k,!0),0<e.length&&(e[m]||(m=e[m[0]]?m[0]:m[1]),
e[g]||(g=e[g[0]]?g[0]:g[1]),f=e[m],e=e[g],f&&b.push(f),e&&(b.push(e),r.push(b),b=[]))))}r.push(b)});a.setShape(this._getPathStringFromPaths(r))}},_clipPolygon:function(a,b){var c=this._getCorners(a,b),d=c.br,e=this._rendererLimits,f=e.clipLimit,g=e.rangeMin,h=e.rangeMax,k=e.clipBBox,l=e.clipSegments,e=this._isPointWithinRange,n=this._isPointWithinBBox,p=this._getClipperIntersection,v=this._getPlaneIndex,z=S._pointLineDistance;if(!e(c.tl,g,h)||!e(d,g,h))t&&this._createSegments(a),c=m.map(a.segments,
function(a){var b=a.args,c=b.length,d=[];a=[];var e;for(e=0;e<c;e+=2){var g=[b[e],b[e+1]],h=[b[e+2],b[e+3]];if(e===c-2){d.push(g);break}var s=n(g,k),q=n(h,k);d.push(g);if(s^q){if(q=p([g,h],l))g=q[1],g[s?"inOut":"outIn"]=!0,d.push(g),a.push([s?"INOUT":"OUTIN",d.length-1,q[0]])}else if(!s){var s=v(g,k),y=v(h,k);-1===s||(-1===y||s===y)||(q=p([g,h],l,!0),0<q.length?(q[s]||(s=q[s[0]]?s[0]:s[1]),q[y]||(y=q[y[0]]?y[0]:y[1]),g=q[s],h=q[y],g&&(g.outIn=!0,d.push(g),a.push(["OUTIN",d.length-1,s])),h&&(h.inOut=
!0,d.push(h),a.push(["INOUT",d.length-1,y]))):r.isArray(s)&&r.isArray(y)&&(q=s.concat(y),q.sort(),"0123"===q.join("")&&(q=[],3===s[0]+s[1]?q.push([f,-f],[-f,f]):q.push([-f,-f],[f,f]),s=z(q[0],[g,h]),g=z(q[1],[g,h]),d.push(s<g?q[0]:q[1]))))}}var t=k[0],u=k[1],w=k[2],x=k[3];m.forEach(d,function(a){a[0]<t&&(a[1]>=u&&a[1]<=x?a[0]=t:(a[0]=t,a[1]=a[1]<u?u:x))});m.forEach(d,function(a){a[1]<u&&(a[0]>=t&&a[0]<=w?a[1]=u:(a[1]=u,a[0]=a[0]<t?t:w))});m.forEach(d,function(a){a[0]>w&&(a[1]>=u&&a[1]<=x?a[0]=w:(a[0]=
w,a[1]=a[1]<u?u:x))});m.forEach(d,function(a){a[1]>x&&(a[0]>=t&&a[0]<=w?a[1]=x:(a[1]=x,a[0]=a[0]<t?t:w))});b=0;c=a.length;if(0<c){do{h=a[b];e=a[(b+1)%c];if(h[2]===e[2]&&"INOUT"===h[0]&&"OUTIN"===e[0])if(g=h[1],e=e[1],g<e)for(g+=1;g<e;g++)d[g][2]=!0;else if(g>e){for(g+=1;g<d.length;g++)d[g][2]=!0;for(g=0;g<e;g++)d[g][2]=!0}b=(b+1)%c}while(0!==b)}c=d[0];b=d[d.length-1];c[2]&&(b[2]=!0,m.some(a,function(a){return 1===a[1]?(d.splice(d.length-1,0,r.clone(d[1])),!0):!1}));d=m.filter(d,function(a){return a[2]?
!1:!0});for(b=0;b<d.length-1;b++)if(c=d[b],(e=d[b+1])&&!(c[0]!==e[0]||c[1]!==e[1]))e.outIn?c.outIn=!0:e.inOut&&(c.inOut=!0),d.splice(b+1,1);c=Math.abs;a=[];for(b=0;b<d.length-1;b++){h=d[b];g=h[0];h=h[1];s=c(g)===f;q=c(h)===f;e=d[b+1];y=e[0];e=e[1];var A=c(y)===f,B=c(e)===f;s&&B?a.push([b+1,[g,e]]):q&&A&&a.push([b+1,[y,h]])}for(b=a.length-1;0<=b;b--)e=a[b],g=d[e[0]-1],c=d[e[0]],!g.outIn&&(!g.inOut&&!c.outIn&&!c.inOut)&&d.splice(e[0],0,e[1]);c=d[0];b=d[d.length-1];(c[0]!==b[0]||c[1]!==b[1])&&d.push(c);
return d}),a.setShape(this._getPathStringFromPaths(c))},_getCorners:function(a,b){if(t){var c=this._map,d=b.getExtent(),e=d.spatialReference,f=c.toScreen(new R(d.xmin,d.ymax,e)),c=c.toScreen(new R(d.xmax,d.ymin,e));return{tl:f,br:c}}f=a.getTransformedBoundingBox();return{tl:f[0],br:f[2]}},_createSegments:function(a){a.shape.path=a.vmlPath;a.segmented=!1;a._confirmSegmented();var b=a.segments;1<b.length&&(a.segments=m.filter(b,function(a,b,e){b=e[b+1];return"M"===a.action&&b&&"L"===b.action?(a.args=
a.args.concat(b.args),!0):!1}))},_getPathStringFromPaths:function(a){t?(a=m.map(a,function(a){return"m "+m.map(a,function(a,b){return(1===b?"l ":"")+a.join(",")}).join(" ")}),a.push("e")):a=m.map(a,function(a){return"M "+m.map(a,function(a){return a.join(",")}).join(" ")});return a.join(" ")},_isPointWithinBBox:function(a,b){var c=b[1],d=b[2],e=b[3],f=a[0],g=a[1];return f>b[0]&&f<d&&g>c&&g<e?!0:!1},_isPointWithinRange:function(a,b,c){var d=a.x;a=a.y;return d<b||a<b||d>c||a>c?!1:!0},_getClipperIntersection:function(a,
b,c){var d,e=S._getLineIntersection2,f=Math.round,g={length:0};for(d=0;4>d;d++){var h=e(a,b[d]);if(h)if(h[0]=f(h[0]),h[1]=f(h[1]),c)g[d]=h,g.length++;else return[d,h]}return c?g:null},_getPlaneIndex:function(a,b){var c=a[0],d=a[1],e=b[0],f=b[1],g=b[2],h=b[3];return c<=e?d>=f&&d<=h?3:d<f?[0,3]:[2,3]:d<=f?c>=e&&c<=g?0:c<e?[3,0]:[1,0]:c>=g?d>=f&&d<=h?1:d<f?[0,1]:[2,1]:d>=h?c>=e&&c<=g?2:c<e?[3,2]:[1,2]:-1},onGraphicAdd:function(){},onGraphicRemove:function(){},onGraphicNodeAdd:function(){},onGraphicNodeRemove:function(){},
onGraphicDraw:function(){},onGraphicsClear:function(){},onRendererChange:function(){},onOpacityChange:function(){},setInfoTemplate:function(a){this.infoTemplate=a},add:function(a,b){if(a._graphicsLayer===this)return a;b||this.graphics.push(a);a._graphicsLayer=this;this._updateExtent(a);this._draw(a);if(!b)this.onGraphicAdd(a);return a},remove:function(a,b){if(!b){var c;if(-1===(c=m.indexOf(this.graphics,a)))return null;a=this.graphics.splice(c,1)[0]}a.getDojoShape()&&this._removeShape(a);a._shape=
a._graphicsLayer=null;this.onGraphicRemove(a);return a},clear:function(a,b){for(var c=this.graphics;0<c.length;)this.remove(c[0]);if(!b)this.onGraphicsClear()},setOpacity:function(a,b){if(b||this.opacity!=a){var c=this._div;c&&(t?(m.forEach(this.graphics,function(b){var c=b._shape;if(b=c&&c.getNode()){var f=c.strokeStyle,g=b.stroke;f&&g&&(g.opacity=f.color.a*a);c=c.fillStyle;f=b.fill;c&&f&&("tile"===f.type?G.set(b,"opacity",a):f.opacity=c.a*a)}}),c._esriIeOpacity=a):this._canvas?G.set(c.getEventSource(),
"opacity",a):c.getEventSource().setAttribute("opacity",a));this.opacity=a;if(!b)this.onOpacityChange(a)}},setRenderer:function(a){this.renderer=a;this._evalSDRenderer();this.onRendererChange()}});w=w(H,{declaredClass:"esri.layers.GraphicsLayer",constructor:function(){this.enableMouseEvents=r.hitch(this,this.enableMouseEvents);this.disableMouseEvents=r.hitch(this,this.disableMouseEvents);this._processEvent=r.hitch(this,this._processEvent);this._initLayer()},_initLayer:function(){this.loaded=!0;this.onLoad(this)},
_setMap:function(){var a=this.inherited("_setMap",arguments);this.enableMouseEvents();return a},_unsetMap:function(){this.disableMouseEvents();this.inherited("_unsetMap",arguments)},_processEvent:function(a){var b=this._map,c=a.target,d;a.screenPoint=new K(a.pageX-b.position.x,a.pageY-b.position.y);for(a.mapPoint=b.toMap(a.screenPoint);c&&!(d=c.e_graphic);)c=c.parentNode;if(d)return a.graphic=d,a},_onMouseOverHandler:function(a){if(this._processEvent(a))this.onMouseOver(a)},_onMouseMoveHandler:function(a){if(this._processEvent(a))this.onMouseMove(a)},
_onMouseDragHandler:function(a){if(this._processEvent(a))this.onMouseDrag(a)},_onMouseOutHandler:function(a){if(this._processEvent(a))this.onMouseOut(a)},_onMouseDownHandler:function(a){this._downGr=this._downPt=null;this._processEvent(a)&&(v.disconnect(this._onmousemove_connect),v.disconnect(this._onmousedrag_connect),this._onmousedrag_connect=v.connect(this._div.getEventSource(),"onmousemove",this,"_onMouseDragHandler"),this._downGr=a.graphic,this._downPt=a.screenPoint.x+","+a.screenPoint.y,this.onMouseDown(a))},
_onMouseUpHandler:function(a){this._upGr=this._upPt=null;this._processEvent(a)&&(v.disconnect(this._onmousedrag_connect),v.disconnect(this._onmousemove_connect),this._onmousemove_connect=v.connect(this._div.getEventSource(),"onmousemove",this,"_onMouseMoveHandler"),this._upGr=a.graphic,this._upPt=a.screenPoint.x+","+a.screenPoint.y,this.onMouseUp(a))},_onClickHandler:function(a){if(this._processEvent(a)){var b=this._downGr,c=this._upGr;b&&(c&&b===c&&this._downPt===this._upPt)&&(t&&(J._ieGraphic=a.graphic),
this.onClick(a))}},_onDblClickHandler:function(a){if(this._processEvent(a))this.onDblClick(a)},onMouseOver:function(){},onMouseMove:function(){},onMouseDrag:function(){},onMouseOut:function(){},onMouseDown:function(){},onMouseUp:function(){},onClick:function(){},onDblClick:function(){},enableMouseEvents:function(){if(!this._mouseEvents){var a=v.connect,b=this._div.getEventSource();O||(this._onmouseover_connect=a(b,"onmouseover",this,"_onMouseOverHandler"),this._onmousemove_connect=a(b,"onmousemove",
this,"_onMouseMoveHandler"),this._onmouseout_connect=a(b,"onmouseout",this,"_onMouseOutHandler"),this._onmousedown_connect=a(b,"onmousedown",this,"_onMouseDownHandler"),this._onmouseup_connect=a(b,"onmouseup",this,"_onMouseUpHandler"),this._onclick_connect=a(b,"onclick",this,"_onClickHandler"),this._ondblclick_connect=a(b,"ondblclick",this,"_onDblClickHandler"));this._mouseEvents=!0}},disableMouseEvents:function(){if(this._mouseEvents){var a=v.disconnect;a(this._onmouseover_connect);a(this._onmousemove_connect);
a(this._onmousedrag_connect);a(this._onmouseout_connect);a(this._onmousedown_connect);a(this._onmouseup_connect);a(this._onclick_connect);a(this._ondblclick_connect);this._mouseEvents=!1}}});w._GraphicsContainer=T;w._GraphicsLayer=H;E("extend-esri")&&(r.setObject("layers.GraphicsLayer",w,J),r.setObject("layers._GraphicsContainer",T,J),r.setObject("layers._GraphicsLayer",H,J));return w});