/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/layers/LabelLayer","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/has dojox/gfx/_base esri/kernel esri/lang esri/SpatialReference esri/graphic esri/layers/GraphicsLayer esri/geometry/Geometry esri/geometry/Extent esri/geometry/Point esri/geometry/Polyline esri/geometry/Polygon esri/symbols/TextSymbol esri/symbols/SimpleLineSymbol".split(" "),function(y,F,H,I,A,J,K,Q,L,M,R,G,N,S,O,P,T){y=y(M,{declaredClass:"esri.layers.LabelLayer",constructor:function(){this._featureLayers=
[];this._zone=[];this._mainStore=[];this._PI=Math.PI;this._PI2=Math.PI/2;this._extent;this._y1=this._x1=this._y0=this._x0=this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1},_refresh:function(){this._zone=[];this._mainStore=[];this._extent=this._map.extent;this._xmin=this._extent.xmin;this._xmax=this._extent.xmax;this._ymin=this._extent.ymin;this._ymax=this._extent.ymax;this._scale=(this._xmax-this._xmin)/this._map.width;var d,a;for(d=0;d<this._featureLayers.length;d++){var b=this._featureLayers[d],
e=b.featureLayer,f=b.renderer,h=b.labelRenderer;if(e.visibleAtMapScale){var c=b.textExpression,g=e.graphics;for(a=0;a<g.length;a++){var k=g[a],q=e._map._convertGeometry(this._extent,k.geometry);if(this._extent.intersects(q)){var l=K.substitute(k.attributes,c);if(null!=l&&""!=F.trim(l)){b=h.getSymbol(k);b.setText(l);var r=b.getWidth()/2,b=b.getHeight()/2,m=0,p=0;if(null!=f){var n=f.getSymbol(k);if(null!=n)if("simplemarkersymbol"==n.type)m=p=A.normalizedLength(n.size)/2;else if("picturemarkersymbol"==
n.type)m=A.normalizedLength(n.width)/2,p=A.normalizedLength(n.height)/2;else if("simplelinesymbol"==n.type||"cartographiclinesymbol"==n.type)p=A.normalizedLength(n.width)/2}this._mainStore.push({fNumber:d,labelWidth:r,labelHeight:b,symbolWidth:m,symbolHeight:p,graphic:k,geometry:q,text:l,lineLabelPosition:this.LE_PLACEONTOP})}}}}}this.process();this.clear();for(d=0;d<this._zone.length;d++)e=this._zone[d],h=this._featureLayers[e.fNumber].labelRenderer,b=h.getSymbol(e.graphic),b.setAngle(e.angle*(180/
this._PI)),b.setText(e.text),h=e.x,f=e.y,b instanceof P&&(a=b.getHeight(),Math.cos(e.angle),e=Math.sin(e.angle),h-=0.25*a*this._scale*e,f-=0.33*a*this._scale),h=new L(new N(h,f,this._extent.spatialReference)),h.setSymbol(b),this.add(h)},addFeatureLayer:function(d,a,b,e){this._featureLayers.push({featureLayer:d,labelRenderer:a,textExpression:b,options:e});H.connect(d,"onUpdateEnd",this,"_refresh")},getFeatureLayer:function(d){return this._featureLayers[d]},process:function(){var d;for(d=this._mainStore.length-
1;0<=d;d--){var a=this._mainStore[d],b=Math.min(a.labelWidth,a.labelHeight),e=a.labelWidth+0*b,b=a.labelHeight+0*b,f=this._featureLayers[a.fNumber].options,h=null!=f&&void 0!=f.lineLabelPlacement?f.lineLabelPlacement:"PlaceAtCenter",c=null!=f&&void 0!=f.lineLabelPosition?f.lineLabelPosition:"Above",g=null!=f&&void 0!=f.pointPriorities?f.pointPriorities:"AboveRight",k=[2,2,1,3,0,2,3,3,2];"AboveLeft"==g?k=[1,2,2,2,0,3,2,3,3]:"AboveCenter"==g?k=[2,1,2,2,0,2,3,3,3]:"AboveRight"==g?k=[2,2,1,3,0,2,3,3,
2]:"CenterLeft"==g?k=[2,2,3,1,0,3,2,2,3]:"CenterCenter"==g?k=[0,0,0,0,1,0,0,0,0]:"CenterRight"==g?k=[3,2,2,3,0,1,3,2,2]:"BelowLeft"==g?k=[2,3,3,2,0,3,1,2,2]:"BelowCenter"==g?k=[3,3,3,2,0,2,2,1,2]:"BelowRight"==g&&(k=[3,3,2,3,0,2,2,2,1]);f=f&&void 0!=f.labelRotation?f.labelRotation:!0;if("point"==a.geometry.type)this.generatePointPositions(a.fNumber,a.graphic,a.geometry,a.text,e,b,a.symbolWidth,a.symbolHeight,k);else if("multipoint"==a.geometry.type){h=a.geometry;for(c=0;c<h.points.length;c++)this.generatePointPositions(a.fNumber,
a.graphic,h.points[c],a.text,e,b,a.symbolWidth,a.symbolHeight,k)}else"polyline"==a.geometry.type?this.generateLinePositions(a.fNumber,a.graphic,a.geometry,a.text,e,b,2*a.symbolHeight+b,h,c,f):"polygon"==a.geometry.type&&this.generatePolygonPositions(a.fNumber,a.graphic,a.geometry,a.text,e,b)}},combineLines:function(d,a){return d},combinePolygons:function(d,a){},generatePointPositions:function(d,a,b,e,f,h,c,g,k){var q=b.x;b=b.y;c=(c+f)*this._scale;g=(g+h)*this._scale;var l,r;for(l=1;3>=l;l++)for(r=
1;9>=r;r++)if(k[r-1]==l)switch(r){case 1:if(this.findPlace(d,a,e,q-c,b+g,0,f,h))return;break;case 2:if(this.findPlace(d,a,e,q,b+g,0,f,h))return;break;case 3:if(this.findPlace(d,a,e,q+c,b+g,0,f,h))return;break;case 4:if(this.findPlace(d,a,e,q-c,b,0,f,h))return;break;case 5:if(this.findPlace(d,a,e,q,b,0,f,h))return;break;case 6:if(this.findPlace(d,a,e,q+c,b,0,f,h))return;break;case 7:if(this.findPlace(d,a,e,q-c,b-g,0,f,h))return;break;case 8:if(this.findPlace(d,a,e,q,b-g,0,f,h))return;break;case 9:if(this.findPlace(d,
a,e,q+c,b-g,0,f,h))return}},generateLinePositions:function(d,a,b,e,f,h,c,g,k,q){var l=f*this._scale*f*this._scale,r,m,p;for(r=0;r<b.paths.length;r++){var n=b.paths[r],t=n.length,s=Math.floor((t-1)/2),u=0!=(t-1)%2?1:-1;"PlaceAtStart"==g&&(s=0,u=1);"PlaceAtEnd"==g&&(s=t-2,u=-1);for(;0<=s&&s<t-1;){for(m=s;m<t;m++){var v=n[s][0],w=n[s][1],x=n[m][0]-v,y=n[m][1]-w;if(x*x+y*y>l){for(var z=Math.atan2(y,x);z>this._PI2;)z-=this._PI;for(;z<-this._PI2;)z+=this._PI;var A=Math.sin(z),D=Math.cos(z),B=0,C=0;"Above"==
k&&(B=c*A*this._scale,C=c*D*this._scale);"Below"==k&&(B=-c*A*this._scale,C=-c*D*this._scale);if(1==m-s){if(this.clipLine(v,w,n[m][0],n[m][1])&&(v=this._x1-this._x0,p=this._y1-this._y0,v*v+p*p>l&&(m=Math.atan2(p,v),x=f/2+2*h,w=x*this._scale*Math.cos(m),x=x*this._scale*Math.sin(m),"PlaceAtStart"==g?(v=this._x0+w,p=this._y0+x):"PlaceAtEnd"==g?(v=this._x1-w,p=this._y1-x):(v=this._x0+v/2,p=this._y0+p/2),this.findPlace(d,a,e,v-B,p+C,q?-m:0,f,h))))return}else{var E=0;for(p=s;p<=m;p++)E=Math.max(E,Math.abs((n[p][1]-
w)*D-(n[p][0]-v)*A));if(E<h&&this.findPlace(d,a,e,v+x/2-B,w+y/2+C,q?-z:0,f,h))return}break}}s+=u}}},generatePolygonPositions:function(d,a,b,e,f,h){var c=this._featureLayers[d].options;if("ManyLabels"==(null!=c?c.howManyLabels:"OneLabel"))for(c=0;c<b.rings.length;c++){var g=this.findCentroid(b.rings[c],this._xmin,this._ymin,this._xmax,this._ymax);this.findPlace(d,a,e,g[0],g[1],0,f,h)}else for(var g=this.findCentroidForFeature(b,this._xmin,this._ymin,this._xmax,this._ymax),k=g[1],q=0,c=0;10>c;c++){q+=
h/4;g=this.findCentroidForFeature(b,this._xmin,k+(q-h/4),this._xmax,k+(q+h/4));if(this.findPlace(d,a,e,g[0],g[1],0,f,h))break;g=this.findCentroidForFeature(b,this._xmin,k-(q+h/4),this._xmax,k-(q-h/4));if(this.findPlace(d,a,e,g[0],g[1],0,f,h))break}},findCentroid:function(d,a,b,e,f){var h=d.length,c=[0,0],g=0,k=d[0][0],q=d[0][1];k>e&&(k=e);k<a&&(k=a);q>f&&(q=f);q<b&&(q=b);for(var l=1;l<h-1;l++){var r=d[l][0],m=d[l][1],p=d[l+1][0],n=d[l+1][1];r>e&&(r=e);r<a&&(r=a);m>f&&(m=f);m<b&&(m=b);p>e&&(p=e);p<
a&&(p=a);n>f&&(n=f);n<b&&(n=b);var t=(r-k)*(n-q)-(p-k)*(m-q);c[0]+=t*(k+r+p);c[1]+=t*(q+m+n);g+=t}c[0]/=3*g;c[1]/=3*g;if(isNaN(c[0])||isNaN(c[1]))return c;b=[];this.fillBuffer(d,b,c);c[0]=this.sortBuffer(b,c[0],a,e);return c},findCentroidForFeature:function(d,a,b,e,f){for(var h=0,c=[0,0],g=0;g<d.rings.length;g++){var k=d.rings[g],q=k.length,l=k[0][0],r=k[0][1];l>e&&(l=e);l<a&&(l=a);r>f&&(r=f);r<b&&(r=b);for(var m=1;m<q-1;m++){var p=k[m][0],n=k[m][1],t=k[m+1][0],s=k[m+1][1];p>e&&(p=e);p<a&&(p=a);n>
f&&(n=f);n<b&&(n=b);t>e&&(t=e);t<a&&(t=a);s>f&&(s=f);s<b&&(s=b);var u=(p-l)*(s-r)-(t-l)*(n-r);c[0]+=u*(l+p+t);c[1]+=u*(r+n+s);h+=u}}c[0]/=3*h;c[1]/=3*h;if(isNaN(c[0])||isNaN(c[1]))return c;b=[];for(m=0;m<d.rings.length;m++)this.fillBuffer(d.rings[m],b,c);c[0]=this.sortBuffer(b,c[0],a,e);return c},fillBuffer:function(d,a,b){for(var e=d.length-1,f=d[0][1]>=d[e][1]?1:-1,h=0;h<=e;h++){var c=h,g=h+1;h==e&&(g=0);var k=d[c][0],c=d[c][1],q=d[g][0],g=d[g][1],l=g>=c?1:-1;if(c<=b[1]&&b[1]<=g||g<=b[1]&&b[1]<=
c)b[1]!=c&&b[1]!=g?(a.push((b[1]-c)*(q-k)/(g-c)+k),f=l):b[1]==c&&b[1]!=g?(f!=l&&a.push(k),f=l):b[1]!=c&&b[1]==g?(a.push(q),f=l):b[1]==c&&b[1]==g&&(1==f&&a.push(k),a.push(q),f=l)}},sortBuffer:function(d,a,b,e){var f=d.length;d.sort();if(0<f){for(var h=0,c=a=0;c<f-1;c+=2){var g=Math.abs(d[c+1]-d[c]);!(d[c]<=b&&d[c+1]<=b)&&(!(d[c]>=e&&d[c+1]>=e)&&g>h)&&(h=g,a=c)}f=d[a];d=d[a+1];f>e&&(f=e);f<b&&(f=b);d>e&&(d=e);d<b&&(d=b);a=(f+d)/2}return a},findPlace:function(d,a,b,e,f,h,c,g){if(isNaN(e)||isNaN(f)||
e<this._xmin||e>this._xmax||f<this._ymin||f>this._ymax)return!1;for(var k=new G(-c*this._scale,-g*this._scale,c*this._scale,g*this._scale,null),q=0;q<this._zone.length;q++){var l=this._zone[q],r=l.angle,m=l.width*this._scale,p=l.height*this._scale,n=l.x-e,t=l.y-f;if(0==h&&0==r){if(l=new G(n-m,t-p,n+m,t+p,null),k.intersects(l))return!1}else{var s=0,u=1;0!=h&&(s=Math.sin(h),u=Math.cos(h));var l=n*u-t*s,n=n*s+t*u,r=r-h,s=Math.sin(r),u=Math.cos(r),v=-m*u- -p*s,t=-m*s+-p*u,r=+m*u- -p*s,w=+m*s+-p*u,m=l+
v,p=n-t,s=l+r,u=n-w,v=l-v,t=n+t,l=l-r,n=n+w,r=new O;r.addRing([[m,p],[s,u],[v,t],[l,n],[m,p]]);if(k.intersects(r))return!1}}for(;h>this._PI2;)h-=this._PI;for(;h<-this._PI2;)h+=this._PI;this._zone.push({fNumber:d,graphic:a,text:b,angle:h,x:e,y:f,width:c,height:g});return!0},clipLine:function(d,a,b,e){for(var f=this.code(d,a),h=this.code(b,e);0!=f||0!=h;){if(0!=(f&h))return!1;var c=b-d,g=e-a;0!=f?(d<this._xmin?(a+=g*(this._xmin-d)/c,d=this._xmin):d>this._xmax?(a+=g*(this._xmax-d)/c,d=this._xmax):a<
this._ymin?(d+=c*(this._ymin-a)/g,a=this._ymin):a>this._ymax&&(d+=c*(this._ymax-a)/g,a=this._ymax),f=this.code(d,a)):(b<this._xmin?(e+=g*(this._xmin-b)/c,b=this._xmin):b>this._xmax?(e+=g*(this._xmax-b)/c,b=this._xmax):e<this._ymin?(b+=c*(this._ymin-e)/g,e=this._ymin):e>this._ymax&&(b+=c*(this._ymax-e)/g,e=this._ymax),h=this.code(b,e))}this._x0=d;this._y0=a;this._x1=b;this._y1=e;return!0},code:function(d,a){return(d<this._xmin?1:0)<<3|(d>this._xmax?1:0)<<2|(a<this._ymin?1:0)<<1|(a>this._ymax?1:0)}});
I("extend-esri")&&F.setObject("layers.LabelLayer",y,J);return y});