//>>built
define("dgrid/editor","dojo/_base/kernel dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/on dojo/aspect dojo/has ./Grid put-selector/put dojo/_base/sniff".split(" "),function(C,q,D,w,l,r,s,x,t){function u(a,c){a.value=c;if("radio"==a.type||"checkbox"==a.type)a.checked=!!c}function y(a,c){if("number"==typeof c)a=isNaN(a)?a:parseFloat(a);else if("boolean"==typeof c)a="true"==a?!0:"false"==a?!1:a;else if(c instanceof Date){var b=new Date(a);a=isNaN(b.getTime())?a:b}return a}function E(a,c,
b,e,g){var f,d,k;if(!(b>=e&&b<=e)&&(f=a.cell(c),d=f.row,k=f.column,k.field&&d))if(f={grid:a,cell:f,rowId:d.id,oldValue:b,value:e,bubbles:!0,cancelable:!0},g&&g.type&&(f.parentType=g.type),l.emit(c,"dgrid-datachange",f))a.updateDirty&&(a.updateDirty(d.id,k.field,e),k.autoSave&&setTimeout(function(){a._trackError("save")},0));else{var m;(m=c.widget)?(m._dgridIgnoreChange=!0,m.set("value",b),setTimeout(function(){m._dgridIgnoreChange=!1},0)):(m=c.input)&&u(m,b);return b}return e}function v(a,c,b,e){if(!b.isValid||
b.isValid()){c=E;var g=(b.domNode||b).parentNode,f=h?n:b._dgridLastValue,d;d="function"==typeof b.get?y(b.get("value")):y(b["checkbox"==b.type||"radio"==b.type?"checked":"value"]);a=c(a,g,f,d,e);h?n=a:b._dgridLastValue=a}}function z(a){var c=a.editor,b=a.editOn,e=a.grid,g="string"!=typeof c,f,d,k;f=a.editorArgs||{};"function"==typeof f&&(f=f.call(e,a));if(g)d=new c(f),g=d.focusNode||d.domNode,g.className+=" dgrid-input",d.connect(d,b?"onBlur":"onChange",function(){d._dgridIgnoreChange||v(e,a,this,
{type:"widget"})});else if(k=function(d){var b=d.target;"_dgridLastValue"in b&&-1<b.className.indexOf("dgrid-input")&&v(e,a,b,d)},a.grid._hasInputListener||(e._hasInputListener=!0,e.on("change",function(a){k(a)})),d=g=t(("textarea"==c?"textarea":"input[type\x3d"+c+"]")+".dgrid-input",q.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},f)),9>s("ie")||s("ie")&&s("quirks"))"radio"==c||"checkbox"==c?l(d,"click",function(a){k(a)}):l(d,"change",function(a){k(a)});l(g,"mousedown",function(a){a.stopPropagation()});
return d}function F(a,c){var b=z(a),e=b.domNode||b,g=b.focusNode||e,f=b.domNode?function(){b.set("value",b._dgridLastValue)}:function(){u(b,b._dgridLastValue);v(a.grid,a,b)};l(g,"keydown",function(d){d=d.keyCode||d.which;27==d?(f(),n=b._dgridLastValue,g.blur()):13==d&&!1!==a.dismissOnEnter&&g.blur()});(a._editorBlurHandle=l.pausable(b,"blur",function(){var d=e.parentNode;a.grid.cell(e);var b=d.children.length-1,c={alreadyHooked:!0};for(d.removeChild(e);b--;)t(d.firstChild,"!");x.appendIfNode(d,a.renderCell(a.grid.row(d).data,
n,d,p?q.delegate(c,p):c));h=n=p=null;a._editorBlurHandle.pause()})).pause();return b}function A(a,c,b,e){(c=a.domNode)||u(a,e);b.innerHTML="";t(b,a.domNode||a);c&&(a._started||a.startup(),a._dgridIgnoreChange=!0,a.set("value",e),setTimeout(function(){a._dgridIgnoreChange=!1},0));a._dgridLastValue=e;h&&(n=e)}function B(a){var c,b,e,g,f,d;a.column||(a=this.cell(a));c=a.column;g=c.field;b=a.element.contents||a.element;if(f=c.editorInstance){if(h!=b&&(!c.canEdit||c.canEdit(a.row.data,e)))return h=b,a=
a.row,e=(e=this.dirty&&this.dirty[a.id])&&g in e?e[g]:c.get?c.get(a.data):a.data[g],A(c.editorInstance,c,b,e),d=new w,setTimeout(function(){f.focus&&f.focus();c._editorBlurHandle&&c._editorBlurHandle.resume();d.resolve(f)},0),d.promise}else if(c.editor&&(f=b.widget||b.input))return d=new w,f.focus&&f.focus(),d.resolve(f),d.promise;return null}var h,n,p;q.getObject("dgrid.editor",!0);return dgrid.editor=function(a,c,b){var e=a.renderCell||x.defaultRenderCell,g=[],f;a||(a={});a.editor=c=c||a.editor||
"text";a.editOn=b=b||a.editOn;f="string"!=typeof c;a.widgetArgs&&(C.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 1.0"),a.editorArgs=a.widgetArgs);r.after(a,"init",b?function(){var b=a.grid;b.edit||(b.edit=B);a.editorInstance=F(a,e)}:function(){var b=a.grid;b.edit||(b.edit=B);f&&g.push(r.before(b,"removeRow",function(c){c=b.cell(c,a.id).element;(c=(c.contents||c).widget)&&c.destroyRecursive()}))});r.after(a,"destroy",function(){D.forEach(g,function(a){a.remove()});a._editorBlurHandle&&
a._editorBlurHandle.remove();b&&f&&a.editorInstance.destroyRecursive()});a.renderCell=b?function(c,f,g,h){if(!h||!h.alreadyHooked)l("TD"==g.tagName?g:g.parentNode,b,function(){p=h;a.grid.edit(this)});return e.call(a,c,f,g,h)}:function(b,c,g,h){if(!a.canEdit||a.canEdit(b,c))b=z(a),A(b,a,g,c),g[f?"widget":"input"]=b;else return e.call(a,b,c,g,h)};return a}});