//>>built
define("dgrid/Grid","dojo/_base/kernel dojo/_base/declare dojo/on dojo/has put-selector/put ./List dojo/_base/sniff".split(" "),function(u,g,w,h,k,x){function p(a,b){b&&b.nodeType&&a.appendChild(b)}var v=8>h("ie")&&!h("quirks"),y=/[^\._a-zA-Z0-9-]/g;g=g("dgrid.Grid",x,{columns:null,cellNavigation:!0,tabableHeader:!0,showHeader:!0,column:function(a){return"string"==typeof a?this.columns[a]:this.cell(a).column},listType:"grid",cell:function(a,b){if(a.row&&a.row instanceof this._Row)return a;a.target&&
a.target.nodeType&&(a=a.target);var c;if(a.nodeType){do{if(this._rowIdToObject[a.id])break;var d=a.columnId;if(d){b=d;c=a;break}a=a.parentNode}while(a&&a!=this.domNode)}if(!c&&"undefined"!=typeof b){var f=this.row(a);if(d=f.element)for(var d=d.getElementsByTagName("td"),e=0;e<d.length;e++)if(d[e].columnId==b){c=d[e];break}}if(null!=a)return{row:f||this.row(a),column:b&&this.column(b),element:c}},_columnsCss:function(a){a.fullSelector=function(){return this.parent.fullSelector()+" .dgrid-cell"};for(var b=
0;b<a.children.length;b++){var c=a.children[b];c.field=c.className=c.selector.substring(1)}return a.children},createRowCells:function(a,b,c){var d=k("table.dgrid-row-table[role\x3dpresentation]"),f=9>h("ie")||h("quirks")?k(d,"tbody"):d,e,r,t,g,p,q,m,n,l,s;c=c||this.subRows;r=0;for(t=c.length;r<t;r++){q=c[r];e=1==t&&!h("ie")?f:k(f,"tr");q.className&&k(e,"."+q.className);g=0;for(p=q.length;g<p;g++){m=q[g];n=m.id;l=m.className||m.field&&"field-"+m.field;l=k(a+(".dgrid-cell.dgrid-cell-padding"+(n?".dgrid-column-"+
n:"")+(l?"."+l:"")).replace(y,"-")+"[role\x3d"+("th"===a?"columnheader":"gridcell")+"]");l.columnId=n;v?(n=k(l,"!dgrid-cell-padding div.dgrid-cell-padding"),l.contents=n):n=l;if(s=m.colSpan)l.colSpan=s;if(s=m.rowSpan)l.rowSpan=s;b(n,m);e.appendChild(l)}}return d},left:function(a,b){return this.cell(this._move(a,-(b||1),"dgrid-cell"))},right:function(a,b){return this.cell(this._move(a,b||1,"dgrid-cell"))},renderRow:function(a,b){var c=this.createRowCells("td",function(d,f){var e=a;f.get?e=f.get(a):
"field"in f&&"_item"!=f.field&&(e=e[f.field]);f.formatter?d.innerHTML=f.formatter(e):f.renderCell?p(d,f.renderCell(a,e,d,b)):null!=e&&d.appendChild(document.createTextNode(e))},b&&b.subRows);return k("div[role\x3drow]\x3e",c)},renderHeader:function(){var a=this,b=this.headerNode,c=b.childNodes.length;for(b.setAttribute("role","row");c--;)k(b.childNodes[c],"!");c=this.createRowCells("th",function(a,b){var e=b.headerNode=a;v&&(a=a.parentNode);var c=b.field;c&&(a.field=c);if(b.renderHeaderCell)p(e,b.renderHeaderCell(e));
else if(b.label||b.field)e.appendChild(document.createTextNode(b.label||b.field));!1!==b.sortable&&(c&&"_item"!=c)&&(a.sortable=!0,a.className+=" dgrid-sortable")},this.subRows&&this.subRows.headerRows);this._rowIdToObject[c.id=this.id+"-header"]=this.columns;b.appendChild(c);w(c,"click,keydown",function(d){if("click"==d.type||32==d.keyCode||!h("opera")&&13==d.keyCode){d=d.target;var c,e;do if(d.sortable)return a._sortNode=d,d=d.field||d.columnId,c=(e=a._sort[0])&&e.attribute==d&&!e.descending,a.set("sort",
d,c);while((d=d.parentNode)&&d!=b)}})},resize:function(){var a=this.headerNode.firstChild,b=this.contentNode,c;this.inherited(arguments);if(!h("ie")||7<h("ie")&&!h("quirks"))if(b.style.width="",b&&a&&(c=a.offsetWidth)!=b.offsetWidth)b.style.width=c+"px"},destroy:function(){this._destroyColumns();this.inherited(arguments)},_setSort:function(a,b){this.inherited(arguments);this._lastSortedArrow&&(k(this._lastSortedArrow,"\x3c!dgrid-sort-up!dgrid-sort-down"),k(this._lastSortedArrow,"!"),delete this._lastSortedArrow);
if(this._sort[0]){var c=this._sort[0].attribute,d=this._sort[0].descending,f=this._sortNode,e,g,h;delete this._sortNode;if(!f)for(h in e=this.columns,e)if(g=e[h],g.field==c){f=g.headerNode;break}f&&(f=f.contents||f,this._lastSortedArrow=k(f.firstChild,"-div.dgrid-sort-arrow.ui-icon[role\x3dpresentation]"),this._lastSortedArrow.innerHTML="\x26nbsp;",k(f,d?".dgrid-sort-down":".dgrid-sort-up"),this.resize())}},styleColumn:function(a,b){return this.addCssRule("#"+this.domNode.id+" .dgrid-column-"+a,b)},
_configColumns:function(a,b){var c=[],d=b instanceof Array,f,e;for(f in b)e=b[f],"string"==typeof e&&(b[f]=e={label:e}),!d&&!e.field&&(e.field=f),f=e.id=e.id||(isNaN(f)?f:a+f),a&&(this.columns[f]=e),this._configColumn&&this._configColumn(e,f,b,a),e.grid=this,"function"===typeof e.init&&e.init(),c.push(e);return d?b:c},_destroyColumns:function(){var a=this.subRows.length,b,c,d,f;this.cleanup();for(b=0;b<a;b++){c=0;for(f=this.subRows[b].length;c<f;c++)d=this.subRows[b][c],"function"===typeof d.destroy&&
d.destroy()}},configStructure:function(){var a=this.subRows;if(a){this.columns={};for(var b=0;b<a.length;b++)a[b]=this._configColumns(b+"-",a[b])}else this.subRows=[this._configColumns("",this.columns)]},_setColumns:function(a){this._destroyColumns();this.subRows=null;this.columns=a;this._updateColumns()},_setSubRows:function(a){this._destroyColumns();this.subRows=a;this._updateColumns()},setColumns:function(a){u.deprecated("setColumns(...)",'use set("columns", ...) instead',"dgrid 1.0");this.set("columns",
a)},setSubRows:function(a){u.deprecated("setSubRows(...)",'use set("subRows", ...) instead',"dgrid 1.0");this.set("subRows",a)},_updateColumns:function(){this.configStructure();this.renderHeader();this.refresh();this._lastCollection&&this.renderArray(this._lastCollection);this.resize()}});g.appendIfNode=p;g.defaultRenderCell=function(a,b,c,d){null!=b&&c.appendChild(document.createTextNode(b))};return g});