//>>built
define("dgrid/List","dojo/_base/array dojo/_base/kernel dojo/_base/declare dojo/on dojo/has ./util/misc dojo/has!touch?./TouchScroll xstyle/has-class put-selector/put dojo/_base/sniff xstyle/css!./css/dgrid.css".split(" "),function(C,t,u,q,h,y,v,z,d){function s(a){var b=a?"."+a.replace(w,"."):"";this._class&&(b="!"+this._class.replace(w,"!")+b);d(this.domNode,b);this._class=a}function x(){return this._class}z("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var n,k=d(document.getElementsByTagName("head")[0],
"style"),l=[],k=k.sheet||k.styleSheet,A=0,w=/ +/g,B=7>h("ie")&&!h("quirks")?function(){var a,b,c;if(this._started&&(a=document.documentElement,b=a.clientWidth,a=a.clientHeight,c=this._prevWinDims||[],c[0]!==b||c[1]!==a))this.resize(),this._prevWinDims=[b,a]}:function(){this._started&&this.resize()};return u("dgrid.List",v?v:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,postscript:function(a,b){var c=this;(this._Row=function(a,b,c){this.id=a;this.data=b;this.element=c}).prototype.remove=
function(){c.removeRow(this.element)};b&&(this.srcNodeRef=b=b.nodeType?b:document.getElementById(b));this.create(a,b)},listType:"list",create:function(a,b){var c=this.domNode=b||d("div"),f;a?(this.params=a,u.safeMixin(this,a),f=a["class"]||a.className||c.className,this._sort=a.sort||[],delete this.sort):this._sort=[];this.observers=[];this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=c.id=c.id||this.id||"dgrid_"+A++;this.buildRendering();f&&s.call(this,
f);this.postCreate&&this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this,c,f,e,g;g=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();a.className="";d(a,"[role\x3dgrid].ui-widget.dgrid.dgrid-"+this.listType);c=this.headerNode=d(a,"div.dgrid-header.dgrid-header-row.ui-widget-header"+(this.showHeader?"":".dgrid-header-hidden"));(h("quirks")||8>h("ie"))&&d(a,
"div.dgrid-spacer");f=this.bodyNode=d(a,"div.dgrid-scroller");f.tabIndex=-1;this.headerScrollNode=d(a,"div.dgrid-header-scroll.dgrid-scrollbar-width.ui-widget-header");e=this.footerNode=d("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));d(a,e);g&&(a.className+=" dgrid-rtl"+(h("webkit")?"":" dgrid-rtl-nonwebkit"));q(f,"scroll",function(e){b.showHeader&&(c.scrollLeft=e.scrollLeft||f.scrollLeft);e.stopPropagation();q.emit(a,"scroll",{scrollTarget:f})});this.configStructure();this.renderHeader();
this.contentNode=this.touchNode=d(this.bodyNode,"div.dgrid-content.ui-widget-content");this._listeners.push(this._resizeHandle=q(window,"resize",y.throttleDelayed(B,this)))},startup:function(){this.inherited(arguments);this._started||(this._started=!0,this.resize(),this.set("sort",this._sort))},configStructure:function(){},resize:function(){var a=this.bodyNode,b=this.headerNode,c=this.footerNode,f=b.offsetHeight,e=this.showFooter?c.offsetHeight:0,g=h("quirks")||7>h("ie");this.headerScrollNode.style.height=
a.style.marginTop=f+"px";a.style.marginBottom=e+"px";g&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-f-e,0)+"px",e&&(c.style.bottom="1px",setTimeout(function(){c.style.bottom=""},0)));n||(f=d(document.body,"div.dgrid-scrollbar-measure"),n=f.offsetWidth-f.clientWidth,d(f,"!"),7===h("ie")&&n++,this.addCssRule(".dgrid-scrollbar-width","width: "+n+"px"),this.addCssRule(".dgrid-scrollbar-height","height: "+n+"px"),17!=n&&!g&&(this.addCssRule(".dgrid-header","right: "+n+"px"),this.addCssRule(".dgrid-rtl-nonwebkit .dgrid-header",
"left: "+n+"px")));g&&(b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0))},addCssRule:function(a,b){var c=l.length;l[c]=(k.cssRules||k.rules).length;k.addRule?k.addRule(a,b):k.insertRule(a+"{"+b+"}",l[c]);return{remove:function(){var a=l[c],b,g=l.length;if(void 0!==a){k.deleteRule?k.deleteRule(a):k.removeRule(a);l[c]=void 0;for(b=c;b<g;b++)l[b]>a&&l[b]--}}}},on:function(a,b){var c=q(this.domNode,a,b);h("dom-addeventlistener")||this._listeners.push(c);return c},cleanup:function(){var a=
this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var c=document.getElementById(b);c&&this.removeRow(c,!0)}for(b=0;b<a.length;b++)(c=a[b])&&c.cancel();this.observers=[];this.preload=null},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this.cleanup();d(this.domNode,"!")},refresh:function(){this.cleanup();this._rowIdToObject={};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,
y:0})},newRow:function(a,b,c,f){if(!b||b.parentNode){var e=this.insertRow(a,b?b.parentNode:this.contentNode,b,f.start+c,f);d(e,".ui-state-highlight");setTimeout(function(){d(e,"!ui-state-highlight")},250);return e}},adjustRowIndices:function(a){if(this.maintainOddEven){var b=a.rowIndex;if(-1<b){do-1<a.rowIndex&&(-1<(a.className+" ").indexOf("dgrid-row ")&&d(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++);while((a=a.nextSibling)&&a.rowIndex!=
b)}}},renderArray:function(a,b,c){function f(a){r=g.insertRow(a,n,null,d++,c);r.observerIndex=k;return r}function e(a){if(h=b?b.parentNode:g.contentNode)h.insertBefore(n,b||null),(r=a[a.length-1])&&g.adjustRowIndices(r);return m=a}c=c||{};var g=this,d=c.start||0,p,m,h;b||(this._lastCollection=a);if(a.observe)var k=this.observers.push(a.observe(function(a,b,e){var f,d;-1<b&&m[b]&&(p=m.splice(b,1)[0],p.parentNode==h&&((f=p.nextSibling)&&b!=e&&f.rowIndex--,g.removeRow(p)),g._processScroll&&g._processScroll());
if(-1<e){d=m[e];if(!d&&(d=m[e-1]))d=(d.connected||d).nextSibling;if(p=g.newRow(a,d,e,c))if(p.observerIndex=k,m.splice(e,0,p),!f||e<b)a=p.previousSibling,f=!a||a.rowIndex+1==p.rowIndex||0==p.rowIndex?p:a;c.count++}b!=e&&f&&g.adjustRowIndices(f)},!0))-1;var n=document.createDocumentFragment();if(a.map){if(m=a.map(f,console.error),m.then)return m.then(e)}else{m=[];for(var l=0,q=a.length;l<q;l++)m[l]=f(a[l])}var r;return e(m)},renderHeader:function(){},_autoId:0,insertRow:function(a,b,c,f,e){var g=e.parentId,
g=this.id+"-row-"+(g?g+"-":"")+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++),d=document.getElementById(g),h=d&&d.previousSibling;if(!d||c&&d.parentNode!=c.parentNode)d&&this.removeRow(d),d=this.renderRow(a,e),d.className=(d.className||"")+" ui-state-default dgrid-row "+(1==f%2?"dgrid-row-odd":"dgrid-row-even"),this._rowIdToObject[d.id=g]=a;b.insertBefore(d,c||null);h&&this.adjustRowIndices(h);d.rowIndex=f;return d},renderRow:function(a,b){return d("div",""+a)},removeRow:function(a,
b){a=a.element||a;delete this._rowIdToObject[a.id];b||d(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,document.getElementById(this.id+"-row-"+b))},cell:function(a){return{row:this.row(a)}},
_move:function(a,b,c,d){var e,g;g=e=a.element;b=b||1;do if(a=e[0>b?"previousSibling":"nextSibling"]){do if((e=a)&&-1<(e.className+" ").indexOf(c+" ")){g=e;b+=0>b?1:-1;break}while(a=(!d||!e.hidden)&&e[0>b?"lastChild":"firstChild"])}else if(e=e.parentNode,e===this.bodyNode||e===this.headerNode)break;while(b);return g},up:function(a,b,c){return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:h("touch")?function(){return this.inherited(arguments)}:
function(a){"undefined"!==typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)},getScrollPosition:h("touch")?function(){return this.inherited(arguments)}:function(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}},get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);
else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:x,_setClass:s,_getClassName:x,_setClassName:s,_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,descending:b}];this.refresh();this._lastCollection&&(a.length&&("string"!=typeof a&&(b=a[0].descending,a=a[0].attribute),this._lastCollection.sort(function(c,d){var e=c[a],g=d[a];void 0===e&&(e="");void 0===g&&(g="");return e==
g?0:e>g==!b?1:-1})),this.renderArray(this._lastCollection))},sort:function(a,b){t.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 1.0");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=a;d(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();a&&(b.scrollLeft=this.getScrollPosition().x)},setShowHeader:function(a){t.deprecated("setShowHeader(...)",'use set("showHeader", ...) instead',"dgrid 1.0");
this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=a;d(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})});