//>>built
define("dgrid/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on ./util/misc put-selector/put".split(" "),function(C,D,E,z,s,F,t,l){return E("dgrid.OnDemandList",[C,D],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,rowHeight:22,queryRowsOverlap:1,pagingDelay:t.defaultDelay,postCreate:function(){this.inherited(arguments);var c=this;F(this.bodyNode,"scroll",t.throttleDelayed(function(f){c._processScroll(f)},
null,this.pagingDelay))},renderQuery:function(c,f,k){var b={query:c,count:0,node:f,options:k};if(!f){var g={node:l(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:b,options:k};b.node=f=l(this.contentNode,"div.dgrid-preload");b.previous=g}f.rowIndex=this.minRowsPerPage;(g=this.preload)?((b.next=g.next)&&this.bodyNode.scrollTop>=g.node.offsetTop?b.previous=g:(b.next=g,b.previous=g.previous),b.previous.next=b,b.next.previous=b):this.preload=b;var m=l(f,"-div.dgrid-loading");l(m,
"div.dgrid-below").innerHTML=this.loadingMessage;k=z.mixin(this.get("queryOptions"),k,{start:0,count:this.minRowsPerPage,query:c});var n=c(k),d=this;s.when(this.renderArray(n,f,k),function(a){return s.when(n.total||n.length,function(c){l(m,"!");var k=a.length;c=c||k;c||(d.noDataNode=l(d.contentNode,"div.dgrid-no-data"),d.noDataNode.innerHTML=d.noDataMessage);for(var g=0,e=0;e<k;e++)g+=d._calcRowHeight(a[e]);k&&g&&(d.rowHeight=g/k);c-=k;b.count=c;f.rowIndex=k;c?f.style.height=Math.min(c*d.rowHeight,
d.maxEmptySpace)+"px":f.style.display="none";d._processScroll();return a})});return n},refresh:function(){this.inherited(arguments);if(this.store){var c=this;this._trackError(function(){return c.renderQuery(function(f){return c.store.query(c.query,f)})})}},_calcRowHeight:function(c){var f=c.previousSibling;return f&&f.offsetTop!=c.offsetTop?c.offsetHeight:0},lastScrollTop:0,_processScroll:function(c){function f(a,c,d,e){var h=b.farOffRemoval,f=a.node;if(c>2*h){for(var g,m=f[d],n=0,p=0,q=[];g=m;){var r=
b._calcRowHeight(g);if(n+r+h>c||0>m.className.indexOf("dgrid-row")&&0>m.className.indexOf("dgrid-loading"))break;var m=g[d],w,s=g.observerIndex;if(s!=w&&-1<w){var t=b.observers,u=t[w];u&&u.cancel();t[w]=0}n+=r;p+=g.count||1;w=s;b.removeRow(g,!0);q.push(g)}a.count+=p;e?(f.rowIndex-=p,k(a)):f.style.height=f.offsetHeight+n+"px";var v=l("div");for(a=0;a<q.length;a++)l(v,q[a]);setTimeout(function(){l(v,"!")},1)}}function k(a,c){a.node.style.height=Math.min(a.count*b.rowHeight,c?Infinity:b.maxEmptySpace)+
"px"}var b=this,g=b.bodyNode;c=c&&c.scrollTop||g.scrollTop;var m=g.offsetHeight+c,n,d,a=b.preload,t=b.lastScrollTop,y=b.bufferRows*b.rowHeight,A=y-b.rowHeight;for(b.lastScrollTop=c;a&&!a.node.offsetWidth;)a=a.previous;for(;a&&a!=n;){n=b.preload;b.preload=a;d=a.node;var e=d.offsetTop;if(m+1+A<e){do a=a.previous;while(a&&!a.node.offsetWidth)}else if(c-1-A>e+d.offsetHeight){do a=a.next;while(a&&!a.node.offsetWidth)}else{var h=((d.rowIndex?c-y:m)-e)/b.rowHeight,e=(m-c+2*y)/b.rowHeight,u=Math.max(Math.min((c-
t)*b.rowHeight,b.maxRowsPerPage/2),b.maxRowsPerPage/-2),e=e+Math.min(Math.abs(u),10);0==d.rowIndex&&(h-=e);h=Math.max(h,0);10>h&&(0<h&&e+h<b.maxRowsPerPage)&&(e+=Math.max(0,h),h=0);e=Math.min(Math.max(e,b.minRowsPerPage),b.maxRowsPerPage,a.count);if(0==e)break;var e=Math.ceil(e),h=Math.min(Math.floor(h),a.count-e),q=z.mixin(b.get("queryOptions"),a.options);a.count-=e;var p=d,v,x=b.queryRowsOverlap;if(u=0<d.rowIndex&&a){var r=a.previous;r&&(f(r,c-(r.node.offsetTop+r.node.offsetHeight),"nextSibling"),
0<h&&r.node==d.previousSibling?(h=Math.min(a.count,h),a.previous.count+=h,k(a.previous,!0),a.count-=h,d.rowIndex+=h,x=0):e+=h);q.start=d.rowIndex-x;d.rowIndex+=e}else a.next&&(f(a.next,a.next.node.offsetTop-m,"previousSibling",!0),p=d.nextSibling,p==a.next.node?(a.next.count+=a.count-h,a.next.node.rowIndex=h+e,k(a.next),a.count=h,x=0):v=!0),q.start=a.count;q.count=Math.min(e+x,b.maxRowsPerPage);v&&(v=p.offsetTop);k(a);d=l(p,"-div.dgrid-loading[style\x3dheight:"+e*b.rowHeight+"px]");l(d,"div.dgrid-"+
(u?"below":"above")).innerHTML=b.loadingMessage;d.count=e;q.query=a.query;var B=a.query(q);if(void 0===b._trackError(function(){return B}))break;(function(a,c,d,e,f){s.when(b.renderArray(f,a,q),function(){p=a.nextSibling;l(a,"!");if(e&&p){var c=b.getScrollPosition();b.scrollTo({x:c.x,y:c.y+p.offsetTop-e,preserveMomentum:!0})}d&&s.when(f.total||f.length,function(a){d.count=a-d.node.rowIndex;k(d)});b._processScroll()})}).call(this,d,g,u,v,B);a=a.previous}}}})});