/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
require({cache:{"url:esri/dijit/analysis/templates/Analysis.html":'\x3cdiv class\x3d"esriAnalysis"\x3e\r\n   \x3cdiv data-dojo-type\x3d"dijit/layout/AccordionContainer"  doLayout\x3d"false" style\x3d"height:600px;width:100%" data-dojo-attach-point\x3d"_leftAccordion"\x3e\r\n      \x3cdiv data-dojo-type\x3d"dijit/layout/ContentPane"  title\x3d"dummy" style\x3d"height:240px;display:none;" data-dojo-attach-point\x3d"_dummyPane"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv data-dojo-type\x3d"dijit/layout/ContentPane"  title\x3d"${i18n.summarizeData}" esriHelpTopic\x3d"SummarizeDataCategory"  data-dojo-attach-point\x3d"_summarizeTools"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv data-dojo-type\x3d"dijit/layout/ContentPane" title\x3d"${i18n.findLocations}" esriHelpTopic\x3d"FindLocationsCategory" data-dojo-attach-point\x3d"_locationTools"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv data-dojo-type\x3d"dijit/layout/ContentPane" title\x3d"${i18n.dataEnrichment}" esriHelpTopic\x3d"EnrichLocationsCategory" data-dojo-attach-point\x3d"_geoenrichTools" \x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv data-dojo-type\x3d"dijit/layout/ContentPane" title\x3d"${i18n.analyzePatterns}" esriHelpTopic\x3d"AnalyzePatternsCategory" data-dojo-attach-point\x3d"_analyzePatTools"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv data-dojo-type\x3d"dijit/layout/ContentPane" title\x3d"${i18n.useProximity}" esriHelpTopic\x3d"UseProximityCategory" data-dojo-attach-point\x3d"_proximityTools"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv data-dojo-type\x3d"dijit/layout/ContentPane" title\x3d"${i18n.manageData}" esriHelpTopic\x3d"ManageDataCategory" data-dojo-attach-point\x3d"_managedataTools" \x3e\r\n      \x3c/div\x3e\r\n  \x3c/div\x3e\x3c!-- end AccordionContainer --\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/analysis/Analysis","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/has dojo/i18n dojo/json dojo/string dojo/dom-style dojo/dom-attr dojo/dom-construct dojo/query dojo/dom-class dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/_OnDijitClickMixin dijit/_FocusMixin dijit/registry dijit/layout/AccordionContainer dijit/layout/ContentPane esri/kernel esri/dijit/analysis/AnalysisToolItem esri/dijit/analysis/utils dojo/text!esri/dijit/analysis/templates/Analysis.html".split(" "),
function(f,n,e,p,l,A,g,h,B,C,k,q,c,m,D,r,s,t,u,v,w,E,F,x,d,y,z){f=n([r,s,t,u,v],{declaredClass:"esri.dijit.analysis.Analysis",templateString:z,basePath:f.toUrl("esri/dijit/analysis"),widgetsInTemplate:!0,i18n:null,helpFileName:"Analysis",constructor:function(b,a){this._pbConnects=[]},postMixInProperties:function(){this.inherited(arguments);this.i18n={};e.mixin(this.i18n,h.getLocalization("esri","jsapi").common);e.mixin(this.i18n,h.getLocalization("esri","jsapi").tocPanel);e.mixin(this.i18n,h.getLocalization("esri",
"jsapi").analysisTools)},startup:function(){this.inherited(arguments);m(".esriAnalysis .dijitAccordionTitle").forEach(function(b,a,c){a=w.byNode(b);a=g("ie")?a.contentWidget.get("esriHelpTopic"):a.contentWidget.get("esrihelptopic");q.set(b,"innerHTML",'\x3cspan class\x3d"esriFloatTrailing helpIcon" esriHelpTopic\x3d"'+a+'" data-dojo-attach-point\x3d"_helpIconNode"\x3e\x3c/span\x3e'+b.innerHTML)},this);this.set("summarizeTools");this.set("locationTools");this.set("geoenrichTools");this.set("analyzePatterns");
this.set("proximityTools");this.set("manageDataTools");this._leftAccordion.startup();m(".esriAnalysis .dijitAccordionInnerContainer.dijitAccordionInnerContainerSelected.dijitSelected").forEach(function(b,a,c){k.set(b,"display","none")});8>=g("ie")&&k.set(this._leftAccordion.domNode,"width","95%");y.initHelpLinks(this.domNode)},destroy:function(){this.inherited(arguments);p.forEach(this._pbConnects,l.disconnect);delete this._pbConnects},_connect:function(b,a,c){this._pbConnects.push(l.connect(b,a,
c))},_setSummarizeToolsAttr:function(){var b=c.create("div"),a=new d({name:this.i18n.aggregatePoints,helpTopic:"AggregatePointsTool",toolIcon:"aggregateIcon"},c.create("div",null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));a=new d({name:this.i18n.summarizeNearby,helpTopic:"SummarizeNearbyTool",toolIcon:"sumNearbyIcon"},c.create("div",null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));a=new d({name:this.i18n.summarizeWithin,
helpTopic:"SummarizeWithinTool",toolIcon:"sumWithinIcon"},c.create("div",null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));this._summarizeTools.set("content",b)},_setLocationToolsAttr:function(){var b=c.create("div");new d({name:this.i18n.findExistingLocations,helpTopic:"FindExistingLocationsTool",toolIcon:"findLocationsIcon"},c.create("div",null,b));new d({name:this.i18n.deriveNewLocations,helpTopic:"DeriveNewLocationsTool",toolIcon:"findNewLocationsIcon"},
c.create("div",null,b));this._locationTools.set("content",b)},_setGeoenrichToolsAttr:function(){var b=c.create("div"),a=new d({name:this.i18n.enrichLayer,helpTopic:"EnrichLayerTool",toolIcon:"geoenrichLayerIcon"},c.create("div",null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));this._geoenrichTools.set("content",b)},_setProximityToolsAttr:function(){var b=c.create("div"),a=new d({name:this.i18n.createBuffers,helpTopic:"CreateBuffersTool",toolIcon:"buffersIcon"},
c.create("div",null,b));this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));a.set("showComingSoonLabel",!1);a=new d({name:this.i18n.createDriveTimeAreas,helpTopic:"CreateDriveTimeAreasTool",toolIcon:"driveIcon"},c.create("div",null,b));k.set(a.optionsDiv,"margin-top","0");a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));a=new d({name:this.i18n.findNearest,helpTopic:"FindNearestTool",toolIcon:"findClosestFacilityIcon"},c.create("div",null,b));a.set("showComingSoonLabel",
!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));this._proximityTools.set("content",b)},_setAnalyzePatternsAttr:function(){var b=c.create("div");new d({name:this.i18n.exploreCorrelations,helpTopic:"ExploreCorrelationsTool",toolIcon:"correlationReporterIcon"},c.create("div",null,b));var a=new d({name:this.i18n.findHotSpots,helpTopic:"FindHotSpotsTool",toolIcon:"findHotSpotsIcon"},c.create("div",null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));
this._analyzePatTools.set("content",b)},_setInterpolateToolsAttr:function(){var b=c.create("div");new d({name:this.i18n.createInterpolatedSurface,helpTopic:"SummarizeWithinTool",toolIcon:"createInterpolatedSurfaceIcon"},c.create("div",null,b));this._interpolateTools.set("content",b)},_setManageDataToolsAttr:function(){var b=c.create("div");new d({name:this.i18n.fieldCalculator,helpTopic:"FieldCalculatorTool",toolIcon:"attributeCalculatorIcon"},c.create("div",null,b));var a=new d({name:this.i18n.dissolveBoundaries,
helpTopic:"DissolveBoundariesTool",toolIcon:"dissolveBoundariesIcon"},c.create("div",null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));a=new d({name:this.i18n.extractData,helpTopic:"ExtractDataTool",toolIcon:"extractDataIcon"},c.create("div",null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));a=new d({name:this.i18n.mergeLayers,helpTopic:"MergeLayersTool",toolIcon:"mergeLayersIcon"},c.create("div",
null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));a=new d({name:this.i18n.overlayLayers,helpTopic:"OverlayLayersTool",toolIcon:"overlayLayersIcon"},c.create("div",null,b));a.set("showComingSoonLabel",!1);this._connect(a,"onToolSelect",e.hitch(this,"onToolSelect"));this._managedataTools.set("content",b)},onToolSelect:function(b){}});g("extend-esri")&&e.setObject("dijit.analysis.Analysis",f,x);return f});