/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/dijit/analysis/AnalysisBase","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/has dojo/i18n dojo/json dojo/Deferred dojo/promise/all dojo/data/ItemFileWriteStore dojo/string dojo/Evented dojo/_base/kernel esri/kernel esri/lang esri/request esri/tasks/Geoprocessor esri/dijit/analysis/utils esri/IdentityManager".split(" "),function(s,n,d,m,g,u,q,v,r,w,x,p,y,z,k,h,l,A,t){n=n([y],{declaredClass:"esri.dijit.analysis.AnalysisBase",isOutputLayerItemUpdated:!1,
analysisGpServer:null,toolName:null,portalUrl:null,jobParams:null,itemParams:null,gp:null,resultParameter:null,signInPromise:null,_jobInfo:null,_popupInfo:null,_toolServiceUrl:null,_counter:null,constructor:function(a){this.isOutputLayerItemUpdated=!1;this._rids=[];this._counter=0;a.analysisGpServer?this._signIn(a.analysisGpServer):a.portalUrl&&(this.portalUrl=a.portalUrl,this._signIn(a.portalUrl,!0))},postMixInProperties:function(){this.inherited(arguments);this.i18n={};d.mixin(this.i18n,q.getLocalization("esri",
"jsapi").common);d.mixin(this.i18n,q.getLocalization("esri","jsapi").analysisTools);d.mixin(this.i18n,q.getLocalization("esri","jsapi").analysisMsgCodes)},execute:function(a){this.jobParams=a.jobParams;this.itemParams=this.jobParams.OutputName?a.itemParams:null;this.signInPromise.then(d.hitch(this,this._checkUser))},_checkUser:function(){var a;if(a=k.id.findCredential(this.portalUrl).userId)a=this.portalUrl+"/sharing/community/users/"+a,l({url:a,content:{f:"json"}}).then(d.hitch(this,this._handleUserProfileResponse),
function(a){this.emit("job-fail",{message:"error getting user response",jobParams:this.jobParams})})},_handleUserProfileResponse:function(a){a.accountId?"account_admin"===a.role||"account_publisher"===a.role||"org_admin"===a.role||"org_publisher"===a.role?this.itemParams?this._checkServiceName(a.accountId):(this._submitGpJob(),this.emit("start",this.jobParams)):this.emit("job-fail",{message:this.i18n.pubRoleMsg,messageCode:"AB_0001",jobParams:this.jobParams}):this.emit("job-fail",{message:this.i18n.orgUsrMsg,
jobParams:this.jobParams})},_checkServiceName:function(a){var b;k.id.findCredential(this.portalUrl);a=this.portalUrl+"/sharing/portals/"+a+"/isServiceNameAvailable";b={name:g.fromJson(this.jobParams.OutputName).serviceProperties.name,type:"Feature Service",f:"json"};l({url:a,content:b}).then(d.hitch(this,function(a){a.available?(this._createService(),this.emit("start",this.jobParams)):this.emit("job-fail",{message:this.i18n.servNameExists,type:"warning",messageCode:"AB_0002",jobParams:this.jobParams})}),
d.hitch(this,function(a){this.emit("job-fail",{message:"error getting service name checked",jobParams:this.jobParams})}))},_createService:function(){var a,b,f;a=k.id.findCredential(this.portalUrl).userId;b=g.fromJson(this.jobParams.OutputName);a&&(f=this.itemParams.folder,a=this.portalUrl+"/sharing/content/users/"+a+(f&&"/"!==f?"/"+f:"")+"/createService",b={createParameters:g.toJson({currentVersion:10.2,serviceDescription:"",hasVersionedData:!1,supportsDisconnectedEditing:!1,hasStaticData:!0,maxRecordCount:2E3,
supportedQueryFormats:"JSON",capabilities:"Query",description:"",copyrightText:"",allowGeometryUpdates:!1,units:"esriMeters",syncEnabled:!1,editorTrackingInfo:{enableEditorTracking:!1,enableOwnershipAccessControl:!1,allowOthersToUpdate:!0,allowOthersToDelete:!0},xssPreventionInfo:{xssPreventionEnabled:!0,xssPreventionRule:"InputOnly",xssInputRule:"rejectInvalid"},tables:[],name:b.serviceProperties.name}),outputType:"featureService",f:"json"},l({url:a,content:b},{usePost:!0}).then(d.hitch(this,this._submitGpJob),
d.hitch(this,this._handleCreateServiceError)))},_handleCreateServiceError:function(a){this.emit("job-fail",{message:a.message,jobParams:this.jobParams})},_getSelf:function(a){return l({url:a+"/sharing/rest/portals/self?culture\x3d"+z.locale,content:{f:"json"},callbackParamName:"callback",timeout:0},{})},_submitGpJob:function(a){var b;this.itemParams&&(this.currentGpItemId=a.itemId,b=g.fromJson(this.jobParams.OutputName),b.itemProperties={itemId:a.itemId},this.jobParams.OutputName=g.toJson(b));this.analysisGpServer?
((!this._toolServiceUrl||!this.gp)&&this.set("toolServiceUrl",this.analysisGpServer+"/"+this.toolName),this.gp.setUpdateDelay(3E3),this.gp.submitJob(this.jobParams,d.hitch(this,this._gpJobComplete),d.hitch(this,this._gpJobStatus),d.hitch(this,this._gpJobFailed)),this.emit("job-submit",this.jobParams)):this._getSelf(this.portalUrl).then(d.hitch(this,function(a){this.analysisGpServer=a.helperServices.analysis&&a.helperServices.analysis.url?a.helperServices.analysis.url:null;this.set("toolServiceUrl",
this.analysisGpServer+"/"+this.toolName);this.gp.setUpdateDelay(3E3);this.gp.submitJob(this.jobParams,d.hitch(this,this._gpJobComplete),d.hitch(this,this._gpJobStatus),d.hitch(this,this._gpJobFailed));this.emit("job-submit",this.jobParams)}))},_updateItem:function(){var a,b,f,c,e;if(a=k.id.findCredential(this.portalUrl).userId){b=this.itemParams.folder;a=this.portalUrl+"/sharing/content/users/"+a+(b&&"/"!==b?"/"+b:"")+"/items/"+this.currentGpItemId+"/update";this.itemParams.typeKeywords="jobUrl:"+
this._toolServiceUrl+"/jobs/"+this._jobInfo.jobId;b=d.mixin({f:"json"},this.itemParams);f={};e={};for(c in this.jobParams)this.jobParams.hasOwnProperty(c)&&("string"===typeof this.jobParams[c]&&-1!==this.jobParams[c].search(/[\{\}\[\]]/g)?e[c]=g.fromJson(this.jobParams[c]):e[c]=this.jobParams[c]);f.analysisInfo={toolName:this.toolName,jobParams:e};this._popupInfo&&(f.layers=[{id:0,popupInfo:this._popupInfo}]);b.text=g.toJson(f);c=l({url:a,content:b},{usePost:!0});c.then(d.hitch(this,this._handleItemUpdate),
d.hitch(this,this._handleUpdateItemError));return c}},_handleItemUpdate:function(a){this.isOutputLayerItemUpdated=!0},_handleItemDataUpdate:function(a){},_handleUpdateItemError:function(a){this.isOutputLayerItemUpdated=!0},_handleErrorResponse:function(a){this.emit("job-fail",a)},_refreshItem:function(){var a,b;if(a=k.id.findCredential(this.portalUrl).userId)return b=this.itemParams.folder,a=this.portalUrl+"/sharing/content/users/"+a+(b&&"/"!==b?"/"+b:"")+"/items/"+this.currentGpItemId+"/refresh",
l({url:a,content:{f:"json"}},{usePost:!0})},_handleItemRefresh:function(a){},_gpJobStatus:function(a){var b="",d=[],c,e;a.jobParams=this.jobParams;"esriJobFailed"===a.jobStatus&&(a.message?b=a.message:a.messages&&(d=m.filter(a.messages,function(a){if("esriJobMessageTypeError"===a.type&&a.description&&-1!==a.description.indexOf("messageCode"))return a.description}),0<d.length&&m.forEach(d,function(a){c=g.fromJson(a.description);e="";c.messageCode?(e=h.isDefined(this.i18n[c.messageCode])?this.i18n[c.messageCode]:
c.message,e=h.isDefined(c.params)?p.substitute(e,c.params):e,b+=e):c.error&&c.error.messageCode&&(e=h.isDefined(this.i18n[c.error.messageCode])?this.i18n[c.error.messageCode]:c.message,e=h.isDefined(c.params)?p.substitute(e,c.params):e,b+=e)},this)),a.message=b,this._deleteItem(!1));this.emit("job-status",a);this._jobInfo=a;this.itemParams&&!this.isOutputLayerItemUpdated&&this._updateItem()},_updateRefreshItem:function(a){var b=[];b.push(this._refreshItem());b.push(this._updateItem());w(b).then(d.hitch(this,
function(b){a.outputLayerName=g.fromJson(this.jobParams.OutputName).serviceProperties.name;a.value.itemId=this.currentGpItemId;a.analysisInfo={toolName:this.toolName,jobParams:this.jobParams};this.emit("job-result",a)}),d.hitch(this,this._handleDeleteItemError))},_gpJobComplete:function(a){"esriJobSucceeded"===a.jobStatus&&(a.jobParams=this.jobParams,this.emit("job-success",a),this.gp.getResultData(a.jobId,this.resultParameter).then(d.hitch(this,function(b){if(b.value.featureSet&&!b.value.url||!this.itemParams)b.value.featureSet.spatialReference=
b.value.layerDefinition.spatialReference,this.jobParams.isProcessInfo?this.gp.getResultData(a.jobId,"ProcessInfo").then(d.hitch(this,function(a){var c=[];m.forEach(a.value,function(a){c.push(g.fromJson(a))},this);b.analysisReport=t.buildReport(c);this.emit("job-result",b)})):this.emit("job-result",b);else if(b.value.url){var f,c;f=b.value.url.replace("/rest/","/admin/").replace("/FeatureServer/0",".FeatureServer")+"/updateDefinition";c={updateDefinition:v.stringify({capabilities:"Query",hasStaticData:!0,
editorTrackingInfo:{enableEditorTracking:!1,enableOwnershipAccessControl:!1,allowOthersToUpdate:!0,allowOthersToDelete:!0}}),f:"json"};l({url:f,content:c},{usePost:!0}).then(d.hitch(this,function(c){!0===c.success?(b.value.layerInfo&&b.value.layerInfo.popupInfo&&(this._popupInfo=b.value.layerInfo.popupInfo),this.jobParams.isProcessInfo?this.gp.getResultData(a.jobId,"ProcessInfo").then(d.hitch(this,function(a){var c=[];m.forEach(a.value,function(a){c.push(g.fromJson(a))},this);this.itemParams.description=
t.buildReport(c);this._updateRefreshItem(b)})):this._updateRefreshItem(b)):this.emit("job-fail",{message:"",jobParams:this.jobParams})}),d.hitch(this,this._handleCreateServiceError))}else this._deleteItem(!1),this.emit("job-fail",{message:this.i18n.emptyResultInfoMsg,type:"warning",jobParams:this.jobParams})})))},_gpJobFailed:function(a){var b="",f=[],c,e;d.clone(a).jobParams=this.jobParams;a.message?b=a.message:a.messages&&(f=m.filter(a.messages,function(a){if("esriJobMessageTypeError"===a.type&&
a.description&&-1!==a.description.indexOf("messageCode"))return a.description}),0<f.length&&m.forEach(f,function(a){c=g.fromJson(a.description);e="";c.messageCode?(e=h.isDefined(this.i18n[c.messageCode])?this.i18n[c.messageCode]:c.message,e=h.isDefined(c.params)?p.substitute(e,c.params):e,b+=e):c.error&&c.error.messageCode&&(e=h.isDefined(this.i18n[c.error.messageCode])?this.i18n[c.error.messageCode]:c.message,e=h.isDefined(c.params)?p.substitute(e,c.params):e,b+=e)},this));a.message=b;this.emit("job-fail",
a)},cancel:function(a){this.gp.cancelJob(a.jobId).then(d.hitch(this,function(a){"esriJobCancelled"===a.jobStatus&&(this.itemParams?this._deleteItem(!0):this.emit("job-cancel",a))}),function(a){})},_deleteItem:function(a){var b,f;if((b=k.id.findCredential(this.portalUrl).userId)&&this.itemParams)f=h.isDefined(this.itemParams.folder)?this.itemParams.folder:"",b=this.portalUrl+"/sharing/content/users/"+b+(f&&"/"!==f?"/"+f:"")+"/items/"+this.currentGpItemId+"/delete",l({url:b,content:{f:"json"}},{usePost:!0}).then(d.hitch(this,
this._handleItemDelete,a),d.hitch(this,this._handleDeleteItemError))},_handleItemDelete:function(a,b){a&&this.emit("job-cancel",b)},_handleDeleteItemError:function(a){this.emit("job-fail",a)},_initFolderStore:function(a,b){this._fportal=new a.Portal(this.portalUrl);this._fportal.signIn().then(d.hitch(this,function(a){this.portalUser=a;this.portalUser.getFolders().then(d.hitch(this,function(a){var d=new x({data:{identifier:"id",label:"name",items:[]}});d.newItem({name:this.portalUser.username,id:""});
m.forEach(a,function(a){d.newItem({name:a.title,id:a.id})});b.resolve(d)}))}))},getFolderStore:function(){var a=new r,b,f,c,e;this.signInPromise.then(d.hitch(this,function(d){k.id.findCredential(this.portalUrl);b=["esri/arcgis/Portal"];f=this._counter++;c=this;this._rids&&this._rids.push(f);s(b,function(b){e=c._rids?m.indexOf(c._rids,f):-1;-1!==e&&(c._rids.splice(e,1),c._initFolderStore(b,a))})}));return a},getCreditsEstimate:function(a,b){var f,c,e;f=this._toolServiceUrl.replace("/"+a,"/exts/Estimate/"+
a);c=new r;e=d.mixin({f:"json"},b);l({url:f,content:e},{usePost:!0}).then(function(a){c.resolve(a)},function(a){c.resolve(a)});return c},_signIn:function(a,b){var f,c,e,g,h;this.signInPromise=new r;b?(f=["esri/arcgis/Portal"],c=this._counter++,e=this,this._rids&&this._rids.push(c),s(f,d.hitch(this,function(b){g=e._rids?m.indexOf(e._rids,c):-1;-1!==g&&(e._rids.splice(g,1),this._portal=new b.Portal(a),this._portal.signIn().then(d.hitch(this,function(a){this._portal.helperServices&&this._portal.helperServices.analysis&&
this._portal.helperServices.analysis.url?(this.analysisGpServer=this._portal.helperServices.analysis.url,l({url:this.analysisGpServer,content:{f:"json"},callbackParamName:"callback"}).then(d.hitch(this,function(a){h=k.id.findCredential(this.analysisGpServer);this.signInPromise.resolve(h)}),d.hitch(this,function(a){this.signInPromise.reject(a)}))):this.signInPromise.resolve(a)}),d.hitch(this,function(a){this.signInPromise.reject(a)})))}))):l({url:a,content:{f:"json"},callbackParamName:"callback"}).then(d.hitch(this,
function(b){b=k.id.findCredential(a);this.portalUrl=k.id.findServerInfo(this._toolServiceUrl).owningSystemUrl;this.signInPromise.resolve(b)}),d.hitch(this,function(a){this.signInPromise.reject(a)}));return this.signInPromise},_setToolServiceUrlAttr:function(a){this._toolServiceUrl=a;this.gp=new A(a)}});u("extend-esri")&&d.setObject("dijit.analysis.AnalysisBase",n,k);return n});