//>>built
define("dgrid/extensions/ColumnResizer","dojo/_base/declare dojo/on dojo/query dojo/_base/lang dojo/dom dojo/dom-geometry dojo/has ../util/misc put-selector/put dojo/_base/html xstyle/css!../css/extensions/ColumnResizer.css".split(" "),function(z,p,k,A,v,w,s,B,l){function x(a){for(var b=a.length,c=b,d=a[0].length,e=Array(b);b--;)e[b]=Array(d);for(var g={},b=0;b<c;b++)for(var m=e[b],f=a[b],q=0,l=0;q<d;q++){var h=f[l],k;if("undefined"==typeof m[q]){m[q]=h.id;if(h.rowSpan&&1<h.rowSpan){k=e;for(var n=
h.rowSpan,p=b,r=q,s=h.id,t=1;t<n;t++)k[p+t][r]=s}if(0<b&&h.colSpan&&1<h.colSpan)for(k=1;k<h.colSpan;k++)if(m[++q]=h.id,h.rowSpan&&1<h.rowSpan)for(var n=e,p=h.rowSpan,r=b,s=q,t=h.id,u=1;u<p;u++)n[r+u][s]=t;g[h.id]=a[0][q].id;l++}}return g}function r(a,b,c,d){if(!(0>=c)){var e={grid:a,columnId:b,width:c,bubbles:!0,cancelable:!0};d&&(e.parentType=d);if(p.emit(a.headerNode,"dgrid-columnresize",e))return d=a._columnStyles[b],c=a.styleColumn(b,"width: "+(("auto"!==c?c+"px":c)+";")),d&&d.remove(),a._columnStyles[b]=
c,!0}}var f,y=0,n={create:function(){f=l("div.dgrid-column-resizer")},destroy:function(){l(f,"!");f=null},show:function(a){a=w.position(a.domNode,!0);f.style.top=a.y+"px";f.style.height=a.h+"px";l(document.body,f)},move:function(a){f.style.left=a+"px"},hide:function(){f.parentNode.removeChild(f)}};return z("dgrid.extensions.ColumnResizer",null,{resizeNode:null,minWidth:40,gridWidth:null,_resizedColumns:!1,buildRendering:function(){this.inherited(arguments);y++||n.create()},destroy:function(){this.inherited(arguments);
--y||n.destroy()},resizeColumnWidth:function(a,b){return r(this,a,b)},configStructure:function(){this._resizedColumns=!1;for(var a in this._columnStyles)this._columnStyles[a].remove();this._columnStyles={};this.inherited(arguments)},_configColumn:function(a,b){this.inherited(arguments);"width"in a&&this.resizeColumnWidth(b,a.width)},renderHeader:function(){this.inherited(arguments);var a=this;a.gridWidth=a.headerNode.clientWidth-1;var b;if(this.columnSets&&this.columnSets.length)for(var c=this.columnSets.length;c--;)b=
A.mixin(b||{},x(this.columnSets[c]));else this.subRows&&1<this.subRows.length&&(b=x(this.subRows));for(var c=k(".dgrid-cell",a.headerNode),d=c.length;d--;){var e=c[d],g=e.columnId,m=a.columns[g],f=e.childNodes;if(m&&!1!==m.resizable){m=l("div.dgrid-resize-header-container");for(e.contents=m;0<f.length;)l(m,f[0]);l(e,m,"div.dgrid-resize-handle.resizeNode-"+g).columnId=b?b[g]:g}}a.mouseMoveListen||(p(a.headerNode,".dgrid-resize-handle:mousedown"+(s("touch")?",.dgrid-resize-handle:touchstart":""),function(b){a._resizeMouseDown(b,
this);a.mouseMoveListen.resume();a.mouseUpListen.resume()}),a.mouseMoveListen=p.pausable(document,"mousemove"+(s("touch")?",touchmove":""),B.throttleDelayed(function(b){a._updateResizerPosition(b)})),a.mouseUpListen=p.pausable(document,"mouseup"+(s("touch")?",touchend":""),function(b){a._resizeMouseUp(b);a.mouseMoveListen.pause();a.mouseUpListen.pause()}),a.mouseMoveListen.pause(),a.mouseUpListen.pause())},_resizeMouseDown:function(a,b){a.preventDefault();v.setSelectable(this.domNode,!1);this._startX=
this._getResizeMouseLocation(a);w.position(this.bodyNode);this._targetCell=k(".dgrid-column-"+b.columnId,this.headerNode)[0];this._updateResizerPosition(a);n.show(this)},_resizeMouseUp:function(a){if(!this._resizedColumns){var b=k(".dgrid-cell",this.headerNode);this.columnSets&&this.columnSets.length?b=b.filter(function(a){return"0"==a.columnId.split("-")[0]}):this.subRows&&1<this.subRows.length&&(b=b.filter(function(a){return"0"==a.columnId.charAt(0)}));var c=b.map(function(a){return a.offsetWidth});
b.forEach(function(a,b){this.resizeColumnWidth(a.columnId,c[b])},this);this._resizedColumns=!0}v.setSelectable(this.domNode,!0);var b=this._targetCell,d=this._getResizeMouseLocation(a)-this._startX,e=b.offsetWidth+d,g=this._getResizedColumnWidths(),f=g.totalWidth,g=g.lastColId,l=k(".dgrid-column-"+g,this.headerNode)[0].offsetWidth;e<this.minWidth&&(e=this.minWidth);r(this,b.columnId,e,a.type)&&b.columnId!=g&&(f+d<this.gridWidth?r(this,g,"auto",a.type):l-d<=this.minWidth&&r(this,g,this.minWidth,a.type),
this.resize());n.hide();delete this._startX;delete this._targetCell},_updateResizerPosition:function(a){if(this._targetCell){a=this._getResizeMouseLocation(a);var b=this._targetCell.offsetWidth,c=a;b+(a-this._startX)<this.minWidth&&(c=this._startX-(b-this.minWidth));n.move(c)}},_getResizeMouseLocation:function(a){var b=0;a.pageX?b=a.pageX:a.clientX&&(b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft);return b},_getResizedColumnWidths:function(){var a=0,b=k(".dgrid-cell",this.headerNode);
this.columnSets&&this.columnSets.length?b=b.filter(function(a){return"0"==a.columnId.split("-")[1]}):this.subRows&&1<this.subRows.length&&(b=b.filter(function(a){return"0"==a.columnId.charAt(0)}));var c=b.length;if(!c)return{};for(var d=b[c-1].columnId;c--;)a+=b[c].offsetWidth;return{totalWidth:a,lastColId:d}}})});