/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/tasks/PrintTask","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/_base/Deferred dojo/has esri/kernel esri/lang esri/deferredUtils esri/tasks/Task esri/renderers/SimpleRenderer esri/geometry/scaleUtils esri/tasks/Geoprocessor esri/tasks/PrintTemplate esri/symbols/PictureMarkerSymbol dojo/dom-construct dojox/gfx/canvas dojo/has!extend-esri?esri/tasks/PrintParameters dojo/has!extend-esri?esri/tasks/LegendLayer".split(" "),function(n,h,l,r,w,s,x,t,y,z,A,B,C,D,F,
E,u){n=n(z,{declaredClass:"esri.tasks.PrintTask",constructor:function(b,g){this.url=b;this.printGp=new C(this.url);this._handler=h.hitch(this,this._handler);g&&g.async&&(this.async=g.async)},_handler:function(b,g,a,d,c){try{var e;this.async?"esriJobSucceeded"===b.jobStatus&&this.printGp.getResultData(b.jobId,"Output_File",h.hitch(this,function(b){e=b.value;this._successHandler([e],"onComplete",a,c)})):(e=b[0].value,this._successHandler([e],"onComplete",a,c))}catch(f){this._errorHandler(f,d,c)}},execute:function(b,
g,a){var d=this._handler,c=this._errorHandler,e=b.template||new D,f=e.exportOptions,k;f&&(k={outputSize:[f.width,f.height],dpi:f.dpi});this._preserveScale=!1===e.preserveScale?!1:!0;var f=e.layoutOptions,p,v=[];if(f){this.legendAll=!1;f.legendLayers?l.forEach(f.legendLayers,function(a,b){var c={};c.id=a.layerId;a.subLayerIds&&(c.subLayerIds=a.subLayerIds);v.push(c)}):this.legendAll=!0;var m,n;if("Miles"===f.scalebarUnit||"Kilometers"===f.scalebarUnit)m="Kilometers",n="Miles";else if("Meters"===f.scalebarUnit||
"Feet"===f.scalebarUnit)m="Meters",n="Feet";p={Miles:"mi",Kilometers:"km",Yards:"yd",Feet:"ft",Meters:"m"};p={titleText:f.titleText,authorText:f.authorText,copyrightText:f.copyrightText,customTextElements:f.customTextElements,scaleBarOptions:{metricUnit:m,metricLabel:p[m],nonMetricUnit:n,nonMetricLabel:p[n]},legendOptions:{operationalLayers:v}}}m=this._getPrintDefinition(b.map);b.outSpatialReference&&(m.mapOptions.spatialReference=b.outSpatialReference.toJson());b.template&&t.isDefined(b.template.showAttribution)&&
(m.mapOptions.showAttribution=b.template.showAttribution);h.mixin(m,{exportOptions:k,layoutOptions:p});this.allLayerslegend&&h.mixin(m.layoutOptions,{legendOptions:{operationalLayers:this.allLayerslegend}});e={Web_Map_as_JSON:r.toJson(t.fixJson(m)),Format:e.format,Layout_Template:e.layout};b.extraParameters&&(e=h.mixin(e,b.extraParameters));var q=new w(y._dfdCanceller);b=function(b,c){d(b,c,g,a,q)};k=function(b){c(b,a,q)};q._pendingDfd=this.async?this.printGp.submitJob(e,b,null,k):this.printGp.execute(e,
b,k);return q},onComplete:function(){},_multipointLayer:function(){this.layerDefinition={name:"multipointLayer",geometryType:"esriGeometryMultipoint",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryMultipoint",features:[]}},_polygonLayer:function(){this.layerDefinition={name:"polygonLayer",geometryType:"esriGeometryPolygon",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPolygon",features:[]}},_pointLayer:function(){this.layerDefinition={name:"pointLayer",
geometryType:"esriGeometryPoint",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPoint",features:[]}},_polylineLayer:function(){this.layerDefinition={name:"polylineLayer",geometryType:"esriGeometryPolyline",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPolyline",features:[]}},_convertSvgSymbol:function(b){if(!(8>=s("ie"))&&b.path){this._canvasHolder||(this._canvasHolder=E.create("div"),this._canSurface=u.createSurface(this._canvasHolder,200,200));
var g=this._canSurface.createObject(u.Path,b.path).setFill(b.color).setStroke(b.outline);"pendingRender"in this._canSurface&&this._canSurface._render(!0);var a=this._canSurface.rawNode.getContext("2d"),d=Math.ceil(g.getBoundingBox().width+g.getBoundingBox().x),c=Math.ceil(g.getBoundingBox().height+g.getBoundingBox().y),e=a.getImageData(g.getBoundingBox().x,g.getBoundingBox().y,d,c);a.canvas.width=d;a.canvas.height=c;a.putImageData(e,0,0);a=a.canvas.toDataURL("image/png");return{type:"esriPMS",imageData:a.substr(22,
a.length),angle:-b.angle,contentType:"image/png",height:b.size?b.size:c-g.getBoundingBox().y,width:b.size?b.size:d-g.getBoundingBox().x,xoffset:b.xoffset,yoffset:b.yoffset}}},_convertSvgRenderer:function(b){"simple"===b.type&&b.symbol&&b.symbol.path?b.symbol=this._convertSvgSymbol(b.symbol):"uniqueValue"===b.type?(b.defaultSymbol&&b.defaultSymbol.path&&(b.defaultSymbol=this._convertSvgSymbol(b.defaultSymbol)),b.uniqueValueInfos&&l.forEach(b.uniqueValueInfos,function(b){b.symbol.path&&(b.symbol=this._convertSvgSymbol(b.symbol))},
this)):"classBreaks"===b.type&&(b.defaultSymbol&&b.defaultSymbol.path&&(b.defaultSymbol=this._convertSvgSymbol(b.defaultSymbol)),b.classBreakInfos&&l.forEach(b.classBreakInfos,function(b){b.symbol.path&&(b.symbol=this._convertSvgSymbol(b.symbol))},this))},_createFeatureCollection:function(b){var g=new this._polygonLayer,a=new this._polylineLayer,d=new this._pointLayer,c=new this._multipointLayer;"esri.layers.FeatureLayer"===b.declaredClass&&(g.layerDefinition.name=a.layerDefinition.name=d.layerDefinition.name=
c.layerDefinition.name=b.name||b.id);b.renderer&&!h.isFunction(b.renderer.attributeField)?(g.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),a.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),d.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),c.layerDefinition.drawingInfo.renderer=b.renderer.toJson()):(delete g.layerDefinition.drawingInfo,delete a.layerDefinition.drawingInfo,delete d.layerDefinition.drawingInfo,delete c.layerDefinition.drawingInfo);b.fields&&(g.layerDefinition.fields=
b.fields,a.layerDefinition.fields=b.fields,d.layerDefinition.fields=b.fields,c.layerDefinition.fields=b.fields);var e,f;for(f=0;f<b.graphics.length;f++){var k=b.graphics[f];if(!1!==k.visible&&k.geometry)switch(e=k.toJson(),e.symbol&&(e.symbol.outline&&e.symbol.outline.color&&e.symbol.outline.color[3])&&(e.symbol.outline.color[3]=255),b.renderer&&(h.isFunction(b.renderer.attributeField)&&!e.symbol)&&(e.symbol=b.renderer.getSymbol(k)?b.renderer.getSymbol(k).toJson():e.symbol),e.symbol&&e.symbol.path&&
(e.symbol=this._convertSvgSymbol(e.symbol)),k.geometry.type){case "polygon":g.featureSet.features.push(e);break;case "polyline":a.featureSet.features.push(e);break;case "point":d.featureSet.features.push(e);break;case "multipoint":c.featureSet.features.push(e)}}e=[];0<d.featureSet.features.length&&e.push(d);0<a.featureSet.features.length&&e.push(a);0<g.featureSet.features.length&&e.push(g);0<c.featureSet.features.length&&e.push(c);l.forEach(e,function(a){a.layerDefinition.drawingInfo&&a.layerDefinition.drawingInfo.renderer&&
this._convertSvgRenderer(a.layerDefinition.drawingInfo.renderer)},this);return{id:b.id,opacity:b.opacity,minScale:b.minScale||0,maxScale:b.maxScale||0,featureCollection:{layers:e}}},_getPrintDefinition:function(b){var g={operationalLayers:this._createOperationalLayers(b)},a=b.extent,d=b.spatialReference;b.spatialReference._isWrappable()&&(a=a._normalize(!0),d=a.spatialReference);a={mapOptions:{showAttribution:b.showAttribution,extent:a.toJson(),spatialReference:d.toJson()}};this._preserveScale&&h.mixin(a.mapOptions,
{scale:B.getScale(b)});b.timeExtent&&h.mixin(a.mapOptions,{time:[b.timeExtent.startTime.getTime(),b.timeExtent.endTime.getTime()]});b={};h.mixin(b,a,g);return b},_createOperationalLayers:function(b){var g,a,d,c,e=[],f=[];this.allLayerslegend=this.legendAll?[]:null;for(g=0;g<b.layerIds.length;g++)if(a=b.getLayer(b.layerIds[g]),a.loaded&&a.visible&&-1===l.indexOf(e,a.id))switch(a.credential&&-1===a.url.indexOf("token\x3d")&&(a.url+="?token\x3d"+a.credential.token),d=a.declaredClass,c={id:a.id,title:a.id,
opacity:a.opacity,minScale:a.minScale||0,maxScale:a.maxScale||0},d){case "esri.layers.ArcGISDynamicMapServiceLayer":var k=[];a._params.dynamicLayers?(d=r.fromJson(a._params.dynamicLayers),l.forEach(d,function(a,b){k.push({id:a.id,layerDefinition:a})})):l.forEach(a.layerInfos,function(b,c){var d={id:b.id,layerDefinition:{definitionExpression:null,layerTimeOptions:null}};a.layerDefinitions&&a.layerDefinitions[b.id]&&(d.layerDefinition.definitionExpression=a.layerDefinitions[b.id]);a.layerTimeOptions&&
a.layerTimeOptions[b.id]&&(d.layerDefinition.layerTimeOptions=a.layerTimeOptions[b.id]);(d.layerDefinition.definitionExpression||d.layerDefinition.layerTimeOptions)&&k.push(d)});c=h.mixin(c,{url:a.url,visibleLayers:a._params.layers?a.visibleLayers:null,layers:k});f.push(c);this.allLayerslegend&&this.allLayerslegend.push({id:a.id,subLayerIds:a.visibleLayers});break;case "esri.layers.ArcGISImageServiceLayer":c=h.mixin(c,{url:a.url,bandIds:a.bandIds,compressionQuality:a.compressionQuality,format:a.format,
interpolation:a.interpolation});a.mosaicRule&&h.mixin(c,{mosaicRule:a.mosaicRule.toJson()});a.renderingRule&&h.mixin(c,{renderingRule:a.renderingRule.toJson()});f.push(c);this.allLayerslegend&&this.allLayerslegend.push({id:a.id});break;case "esri.layers.WMSLayer":c=h.mixin(c,{url:a.url,title:a.title,type:"wms",version:a.version,transparentBackground:a.imageTransparency,visibleLayers:a.visibleLayers});f.push(c);this.allLayerslegend&&this.allLayerslegend.push({id:a.id,subLayerIds:a.visibleLayers});
break;case "esri.virtualearth.VETiledLayer":d=a.mapStyle;"aerialWithLabels"===d&&(d="Hybrid");c=h.mixin(c,{visibility:a.visible,type:"BingMaps"+d,culture:a.culture,key:a.bingMapsKey});f.push(c);break;case "esri.layers.OpenStreetMapLayer":c=h.mixin(c,{type:"OpenStreetMap",url:a.tileServers[0]});f.push(c);break;case "esri.layers.WMTSLayer":c=h.mixin(c,{url:a.url,type:"wmts",layer:a.layerInfos[0].identifier,style:a.layerInfos[0].style,format:a.layerInfos[0].format,tileMatrixSet:a.layerInfos[0].tileMatrixSet});
f.push(c);break;case "esri.layers.MapImageLayer":d=a.getImages();l.forEach(d,function(b,d){b.href&&(c={id:a.id+"_image"+d,type:"image",title:a.id,minScale:a.minScale||0,maxScale:a.maxScale||0,opacity:a.opacity,extent:b.extent.toJson(),url:b.href},f.push(c))});break;case "esri.layers.WebTiledLayer":d=a.url.replace(/\$\{/g,"{");c=h.mixin(c,{type:"WebTiledLayer",urlTemplate:d,credits:a.copyright});a.subDomains&&0<a.subDomains.length&&(c.subDomains=a.subDomains);f.push(c);break;default:if(a.getTileUrl||
a.getImageUrl)c=h.mixin(c,{url:a.url}),f.push(c)}for(g=0;g<b.graphicsLayerIds.length;g++)if(a=b.getLayer(b.graphicsLayerIds[g]),a.loaded&&a.visible&&-1===l.indexOf(e,a.id))switch(d=a.declaredClass,d){case "esri.layers.FeatureLayer":if(a.url&&a.renderer&&h.isString(a.renderer.attributeField)&&a._getField(a.renderer.attributeField,!0))if(a.credential&&-1===a.url.indexOf("token\x3d")&&(a.url+="?token\x3d"+a.credential.token),c={id:a.id,url:a.url,title:a.id,opacity:a.opacity,minScale:a.minScale||0,maxScale:a.maxScale||
0,layerDefinition:{drawingInfo:{renderer:a.renderer.toJson()}}},this._convertSvgRenderer(c.layerDefinition.drawingInfo.renderer),a._params.source&&(d=a._params.source.toJson(),h.mixin(c.layerDefinition,{source:d})),a.getDefinitionExpression()&&h.mixin(c.layerDefinition,{definitionExpression:a.getDefinitionExpression()}),2!==a.mode)0<a.getSelectedFeatures().length&&(d=l.map(a.getSelectedFeatures(),function(b){return b.attributes[a.objectIdField]}),0<d.length&&a.getSelectionSymbol()&&h.mixin(c,{selectionObjectIds:d,
selectionSymbol:a.getSelectionSymbol().toJson()}));else{d=l.map(a.getSelectedFeatures(),function(b){return b.attributes[a.objectIdField]});if(0===d.length||!a._params.drawMode)break;h.mixin(c.layerDefinition,{objectIds:d});d=null;a.getSelectionSymbol()&&(d=new A(a.getSelectionSymbol()));h.mixin(c.layerDefinition.drawingInfo,{renderer:d&&d.toJson()})}else c=this._createFeatureCollection(a);f.push(c);this.allLayerslegend&&this.allLayerslegend.push({id:a.id});break;case "esri.layers.GraphicsLayer":c=
this._createFeatureCollection(a),f.push(c),this.allLayerslegend&&this.allLayerslegend.push({id:a.id})}b.graphics&&0<b.graphics.graphics.length&&(c=this._createFeatureCollection(b.graphics),f.push(c));return f}});s("extend-esri")&&h.setObject("tasks.PrintTask",n,x);return n});