/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/IdentityManagerBase","dojo/_base/declare dojo/_base/config dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/_base/url dojo/has dojo/cookie esri/kernel esri/config esri/lang esri/ServerInfo esri/urlUtils esri/deferredUtils esri/request esri/Evented".split(" "),function(F,w,m,h,G,y,q,J,v,k,A,s,B,l,H,C,x){var z={},D=function(a){var b=(new q(a.owningSystemUrl)).host;a=(new q(a.server)).host;var c=/.+\.arcgis\.com$/i;return c.test(b)&&c.test(a)},E=function(a,b){return!(!D(a)||
!b||!h.some(b,function(b){return b.test(a.server)}))},t;x=F(x,{declaredClass:"esri.IdentityManagerBase",constructor:function(){this._portalConfig=m.getObject("esriGeowConfig");this.serverInfos=[];this.credentials=[];this._soReqs=[];this._xoReqs=[];this._portals=[]},defaultTokenValidity:60,tokenValidity:null,signInPage:null,useSignInPage:!0,_busy:null,_gwTokenUrl:"/sharing/generateToken",_agsRest:"/rest/services",_agsPortal:/\/sharing(\/|$)/i,_agsAdmin:/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i,
_adminSvcs:/\/admin\/services(\/|$)/i,_agolSuffix:".arcgis.com",_gwDomains:[{regex:/https?:\/\/www\.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/dev\.arcgis\.com/i,tokenServiceUrl:"https://dev.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*dev[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://devext.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*qa[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://qaext.arcgis.com/sharing/generateToken"},
{regex:/https?:\/\/.*.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"}],_legacyFed:[],_regexSDirUrl:/http.+\/rest\/services\/?/ig,_regexServerType:/(\/(MapServer|GeocodeServer|GPServer|GeometryServer|ImageServer|NAServer|FeatureServer|GeoDataServer|GlobeServer|MobileServer|GeoenrichmentServer)).*/ig,_gwUser:/http.+\/users\/([^\/]+)\/?.*/i,_gwItem:/http.+\/items\/([^\/]+)\/?.*/i,_gwGroup:/http.+\/groups\/([^\/]+)\/?.*/i,_errorCodes:[499,498,403,401],_publicUrls:[/\/arcgis\/tokens/i,
/\/sharing\/generatetoken/i,/\/rest\/info/i],registerServers:function(a){var b=this.serverInfos;b?(a=h.filter(a,function(a){return!this.findServerInfo(a.server)},this),this.serverInfos=b.concat(a)):this.serverInfos=a;h.forEach(a,function(a){a.owningSystemUrl&&this._portals.push(a.owningSystemUrl);if(a.hasPortal){var b=A.defaults.io.corsEnabledServers,e=this._getOrigin(a.tokenServiceUrl);l.canUseXhr(a.server)||b.push(a.server.replace(/^https?:\/\//i,""));l.canUseXhr(e)||b.push(e.replace(/^https?:\/\//i,
""))}},this)},registerToken:function(a){var b=this._sanitizeUrl(a.server),c=this.findServerInfo(b),d;c||(c=new B,c.server=this._getOrigin(b),c.tokenServiceUrl=this._getTokenSvcUrl(b),c.hasPortal=!0,this.registerServers([c]));(d=this.findCredential(b,a.userId))?m.mixin(d,a):(d=new t({userId:a.userId,server:c.server,token:a.token,expires:a.expires,ssl:a.ssl,scope:this._isServerRsrc(b)?"server":"portal"}),d.resources=[b],this.credentials.push(d));d.onTokenChange(!1)},toJson:function(){return s.fixJson({serverInfos:h.map(this.serverInfos,
function(a){return a.toJson()}),credentials:h.map(this.credentials,function(a){return a.toJson()})})},initialize:function(a){if(a){m.isString(a)&&(a=y.fromJson(a));var b=a.serverInfos;a=a.credentials;if(b){var c=[];h.forEach(b,function(a){a.server&&a.tokenServiceUrl&&c.push(a.declaredClass?a:new B(a))});c.length&&this.registerServers(c)}a&&h.forEach(a,function(a){a.userId&&(a.server&&a.token&&a.expires&&a.expires>(new Date).getTime())&&(a=a.declaredClass?a:new t(a),a.onTokenChange(),this.credentials.push(a))},
this)}},findServerInfo:function(a){var b;a=this._sanitizeUrl(a);h.some(this.serverInfos,function(c){l.hasSameOrigin(c.server,a,!0)&&(b=c);return!!b});return b},findCredential:function(a,b){var c,d;a=this._sanitizeUrl(a);d=this._isServerRsrc(a)?"server":"portal";b?h.some(this.credentials,function(e){l.hasSameOrigin(a,e.server,!0)&&(b===e.userId&&e.scope===d)&&(c=e);return!!c},this):h.some(this.credentials,function(b){l.hasSameOrigin(a,b.server,!0)&&(-1!==this._getIdenticalSvcIdx(a,b)&&b.scope===d)&&
(c=b);return!!c},this);return c},getCredential:function(a,b){var c,d;s.isDefined(b)&&(m.isObject(b)?(c=!!b.token,d=b.error):c=b);a=this._sanitizeUrl(a);var e=new G(H._dfdCanceller),g;g=this._isAdminResource(a);var f=c&&this._doPortalSignIn(a)?v("esri_auth"):null;c=c?this.findCredential(a):null;if(f||c)return f=f&&y.fromJson(f),g=Error("You are currently signed in as: '"+(f&&f.email||c&&c.userId)+"'. You do not have access to this resource: "+a),g.code="IdentityManagerBase.1",g.httpCode=d&&d.httpCode,
g.messageCode=d?d.messageCode:null,g.subcode=d?d.subcode:null,g.details=d?d.details:null,g.log=w.isDebug,e.errback(g),e;if(d=this._findCredential(a,b))return e.callback(d),e;if(d=this.findServerInfo(a))!d.hasServer&&this._isServerRsrc(a)&&(d._restInfoDfd=this._getTokenSvcUrl(a,!0),d.hasServer=!0);else{f=this._getTokenSvcUrl(a);if(!f)return g=Error("Unknown resource - could not find token service endpoint."),g.code="IdentityManagerBase.2",g.log=w.isDebug,e.errback(g),e;d=new B;d.server=this._getOrigin(a);
m.isString(f)?(d.tokenServiceUrl=f,d._selfDfd=this._getPortalSelf(d,a),d.hasPortal=!0):(d._restInfoDfd=f,d.hasServer=!0);this.registerServers([d])}return this._enqueue(a,d,b,e,g)},getResourceName:function(a){return this._isRESTService(a)?a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"")||"":this._gwUser.test(a)&&a.replace(this._gwUser,"$1")||this._gwItem.test(a)&&a.replace(this._gwItem,"$1")||this._gwGroup.test(a)&&a.replace(this._gwGroup,"$1")||""},generateToken:function(a,b,c){var d,
e,g,f,h,I,r=new q(window.location.href.toLowerCase()),p=v("esri_auth"),u;f=a.shortLivedTokenValidity;var n=k.id.tokenValidity||f||k.id.defaultTokenValidity;n>f&&(n=f);c&&(d=c.isAdmin,e=c.serverUrl,g=c.token,I=c.ssl,a.customParameters=c.customParameters);if(d)f=a.adminTokenServiceUrl;else if(f=a.tokenServiceUrl,h=new q(f.toLowerCase()),p&&(p=y.fromJson(p),u=(u=p.auth_tier)&&u.toLowerCase()),"web"===u&&!b&&!I&&"http"===r.scheme&&(l.hasSameOrigin(r.uri,f,!0)||"https"===h.scheme&&r.host===h.host&&"7080"===
r.port&&"7443"===h.port))f=f.replace(/^https:/i,"http:").replace(/:7443/i,":7080");c=C(m.mixin({url:f,content:m.mixin({request:"getToken",username:b&&b.username,password:b&&b.password,serverUrl:e,token:g,expiration:n,referer:d||-1!==a.tokenServiceUrl.toLowerCase().indexOf("/sharing/generatetoken")?window.location.host:null,client:d?"referer":null,f:"json"},a.customParameters),handleAs:"json"},c&&c.ioArgs),{usePost:!0,disableIdentityLookup:!0,useProxy:this._useProxy(a,c)});c.addCallback(function(c){if(!c||
!c.token)return c=Error("Unable to generate token"),c.code="IdentityManagerBase.3",c.log=w.isDebug,c;var d=a.server;z[d]||(z[d]={});b&&(z[d][b.username]=b.password);c.validity=n;return c});c.addErrback(function(a){});return c},isBusy:function(){return!!this._busy},setRedirectionHandler:function(a){this._redirectFunc=a},setProtocolErrorHandler:function(a){this._protocolFunc=a},signIn:function(){},_findCredential:function(a,b){var c=-1,d,e,g,f,k=b&&b.token;d=b&&b.resource;var m=this._isServerRsrc(a)?
"server":"portal",r=h.filter(this.credentials,function(b){return l.hasSameOrigin(b.server,a,!0)&&b.scope===m});a=d||a;if(r.length)if(1===r.length)if(d=r[0],g=(e=(f=this.findServerInfo(d.server))&&f.owningSystemUrl)&&this.findCredential(e,d.userId),c=this._getIdenticalSvcIdx(a,d),k)-1!==c&&(d.resources.splice(c,1),this._removeResource(a,g));else return-1===c&&d.resources.push(a),this._addResource(a,g),d;else{var p,u;h.some(r,function(b){u=this._getIdenticalSvcIdx(a,b);return-1!==u?(p=b,g=(e=(f=this.findServerInfo(p.server))&&
f.owningSystemUrl)&&this.findCredential(e,p.userId),c=u,!0):!1},this);if(k)p&&(p.resources.splice(c,1),this._removeResource(a,g));else if(p)return this._addResource(a,g),p}},_addResource:function(a,b){b&&-1===this._getIdenticalSvcIdx(a,b)&&b.resources.push(a)},_removeResource:function(a,b){var c=-1;b&&(c=this._getIdenticalSvcIdx(a,b),-1<c&&b.resources.splice(c,1))},_useProxy:function(a,b){return b&&b.isAdmin&&!l.hasSameOrigin(a.adminTokenServiceUrl,window.location.href)||!this._isPortalDomain(a.tokenServiceUrl)&&
10.1==a.currentVersion&&!l.hasSameOrigin(a.tokenServiceUrl,window.location.href)},_getOrigin:function(a){a=new q(a);return a.scheme+"://"+a.host+(s.isDefined(a.port)?":"+a.port:"")},_sanitizeUrl:function(a){a=l.fixUrl(m.trim(a));var b=(A.defaults.io.proxyUrl||"").toLowerCase(),c=b?a.toLowerCase().indexOf(b+"?"):-1;-1!==c&&(a=a.substring(c+b.length+1));return l.urlToObject(a).path},_isRESTService:function(a){return-1<a.indexOf(this._agsRest)},_isAdminResource:function(a){return this._agsAdmin.test(a)||
this._adminSvcs.test(a)},_isServerRsrc:function(a){return this._isRESTService(a)||this._isAdminResource(a)},_isIdenticalService:function(a,b){var c;if(this._isRESTService(a)&&this._isRESTService(b)){var d=this._getSuffix(a).toLowerCase(),e=this._getSuffix(b).toLowerCase();c=d===e;c||(c=/(.*)\/(MapServer|FeatureServer).*/ig,c=d.replace(c,"$1")===e.replace(c,"$1"))}else this._isAdminResource(a)&&this._isAdminResource(b)?c=!0:!this._isServerRsrc(a)&&(!this._isServerRsrc(b)&&this._isPortalDomain(a))&&
(c=!0);return c},_isPortalDomain:function(a){a=a.toLowerCase();var b=(new q(a)).authority,c=this._portalConfig,d=-1!==b.indexOf(this._agolSuffix);!d&&c&&(d=l.hasSameOrigin(c.restBaseUrl,a,!0));if(!d){if(!this._arcgisUrl&&(c=m.getObject("esri.arcgis.utils.arcgisUrl")))this._arcgisUrl=(new q(c)).authority;this._arcgisUrl&&(d=this._arcgisUrl.toLowerCase()===b)}d||(d=h.some(this._portals,function(b){return l.hasSameOrigin(b,a,!0)}));return d=d||this._agsPortal.test(a)},_isIdProvider:function(a,b){var c=
-1,d=-1;h.forEach(this._gwDomains,function(e,f){-1===c&&e.regex.test(a)&&(c=f);-1===d&&e.regex.test(b)&&(d=f)});var e=!1;if(-1<c&&-1<d)if(0===c||4===c){if(0===d||4===d)e=!0}else if(1===c){if(1===d||2===d)e=!0}else 2===c?2===d&&(e=!0):3===c&&3===d&&(e=!0);if(!e){var g=this.findServerInfo(b),f=g&&g.owningSystemUrl;f&&(D(g)&&this._isPortalDomain(f)&&this._isIdProvider(a,f))&&(e=!0)}return e},_isPublic:function(a){a=this._sanitizeUrl(a);return h.some(this._publicUrls,function(b){return b.test(a)})},_getIdenticalSvcIdx:function(a,
b){var c=-1;h.some(b.resources,function(b,e){return this._isIdenticalService(a,b)?(c=e,!0):!1},this);return c},_getSuffix:function(a){return a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"$1")},_getTokenSvcUrl:function(a){var b,c;if((b=this._isRESTService(a))||this._isAdminResource(a))return c=a.toLowerCase().indexOf(b?this._agsRest:"/admin/"),b=a.substring(0,c)+"/admin/generateToken",a=a.substring(0,c)+"/rest/info",c=C({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),
c.adminUrl_=b,c;if(this._isPortalDomain(a)){var d="";h.some(this._gwDomains,function(b){b.regex.test(a)&&(d=b.tokenServiceUrl);return!!d});d||h.some(this._portals,function(b){l.hasSameOrigin(b,a,!0)&&(d=b+this._gwTokenUrl);return!!d},this);d||(c=a.toLowerCase().indexOf("/sharing"),-1!==c&&(d=a.substring(0,c)+this._gwTokenUrl));d||(d=this._getOrigin(a)+this._gwTokenUrl);d&&(b=(new q(a)).port,/^http:\/\//i.test(a)&&"7080"===b&&(d=d.replace(/:7080/i,":7443")),d=d.replace(/http:/i,"https:"));return d}if(-1!==
a.toLowerCase().indexOf("premium.arcgisonline.com"))return"https://premium.arcgisonline.com/server/tokens"},_getPortalSelf:function(a,b){var c=a.tokenServiceUrl.replace(/\/sharing\/generatetoken/i,"/sharing/rest/portals/self");return C({url:/^http:/i.test(b)?c.replace(/^https:/i,"http:").replace(/:7443/i,":7080"):c,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{crossOrigin:!1,disableIdentityLookup:!0})},_hasPortalSession:function(){return v.isSupported()?!!v("esri_auth"):!1},_doPortalSignIn:function(a){if(v.isSupported()){var b=
v("esri_auth"),c=this._portalConfig,d=window.location.href,e=this.findServerInfo(a);if((c||this._isPortalDomain(d)||b)&&(this._isPortalDomain(a)||e&&e.owningSystemUrl&&this._isPortalDomain(e.owningSystemUrl))&&(this._isIdProvider(d,a)||c&&(l.hasSameOrigin(c.restBaseUrl,a,!0)||this._isIdProvider(c.restBaseUrl,a))||l.hasSameOrigin(d,a,!0))&&this.useSignInPage)return!0}return!1},_checkProtocol:function(a,b,c,d){var e=!0;d=d?b.adminTokenServiceUrl:b.tokenServiceUrl;if(0===m.trim(d).toLowerCase().indexOf("https:")&&
0!==window.location.href.toLowerCase().indexOf("https:")&&(!A.defaults.io.useCors||!l.canUseXhr(d)&&!l.canUseXhr(l.getProxyUrl(!0).path)))e=this._protocolFunc?!!this._protocolFunc({resourceUrl:a,serverInfo:b}):!1,e||(a=Error("Aborted the Sign-In process to avoid sending password over insecure connection."),a.code="IdentityManagerBase.4",a.log=w.isDebug,console.log(a.message),c(a));return e},_enqueue:function(a,b,c,d,e,g){d||(d=new G(H._dfdCanceller));d.resUrl_=a;d.sinfo_=b;d.options_=c;d.admin_=e;
d.refresh_=g;this._busy?l.hasSameOrigin(a,this._busy.resUrl_,!0)?this._soReqs.push(d):this._xoReqs.push(d):this._doSignIn(d);return d},_doSignIn:function(a){this._busy=a;var b=this,c=function(c){var d=a.options_&&a.options_.resource,e=a.resUrl_,f=a.refresh_;-1===h.indexOf(b.credentials,c)&&(f&&-1!==h.indexOf(b.credentials,f)?(f.userId=c.userId,f.token=c.token,f.expires=c.expires,f.validity=c.validity,f.ssl=c.ssl,f.creationTime=c.creationTime,c=f):b.credentials.push(c));c.resources||(c.resources=[]);
c.resources.push(d||e);c.scope=b._isServerRsrc(e)?"server":"portal";c.onTokenChange();var d=b._soReqs,g={};b._soReqs=[];h.forEach(d,function(a){if(!this._isIdenticalService(e,a.resUrl_)){var b=this._getSuffix(a.resUrl_);g[b]||(g[b]=!0,c.resources.push(a.resUrl_))}},b);a.callback(c);h.forEach(d,function(a){a.callback(c)});b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;b._soReqs.length&&b._doSignIn(b._soReqs.shift());b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},d=function(c){a.errback(c);b._busy=a.resUrl_=
a.sinfo_=a.refresh_=null;b._soReqs.length&&b._doSignIn(b._soReqs.shift());b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},e=function(e,f){var g=a.sinfo_;if(b._doPortalSignIn(a.resUrl_)){var n=v("esri_auth"),h=b._portalConfig;if(n)n=y.fromJson(n),c(new t({userId:n.email,server:g.server,token:n.token,expires:null}));else{var n="",k=window.location.href,n=b.signInPage?b.signInPage:h?h.baseUrl+h.signin:b._isIdProvider(k,a.resUrl_)?b._getOrigin(k)+"/home/signin.html":g.tokenServiceUrl.replace(/\/sharing\/generatetoken/i,
"")+"/home/signin.html",n=n.replace(/http:/i,"https:");h&&!1===h.useSSL&&(n=n.replace(/https:/i,"http:"));0===k.toLowerCase().replace("https","http").indexOf(n.toLowerCase().replace("https","http"))?(g=Error("Cannot redirect to Sign-In page from within Sign-In page. URL of the resource that triggered this workflow: "+a.resUrl_),g.code="IdentityManagerBase.5",g.log=w.isDebug,d(g)):b._redirectFunc?b._redirectFunc({signInPage:n,returnUrlParamName:"returnUrl",returnUrl:k,resourceUrl:a.resUrl_,serverInfo:g}):
window.location=n+"?returnUrl\x3d"+window.escape(k)}}else e?c(new t({userId:e,server:g.server,token:null,expires:null,ssl:!!f})):b._checkProtocol(a.resUrl_,g,d,a.admin_)&&(h=a.options_,a.admin_&&(h=h||{},h.isAdmin=!0),a._pendingDfd=b.signIn(a.resUrl_,g,h).addCallbacks(c,d))},g=function(){var e=a.sinfo_,f=e.owningSystemUrl,g=a.options_,n,k,l;g&&(n=g.token,k=g.error);l=b._findCredential(f,{token:n,resource:a.resUrl_});!l&&D(e)&&h.some(b.credentials,function(a){this._isIdProvider(f,a.server)&&(l=a);
return!!l},b);l?(g=b.findCredential(a.resUrl_,l.userId))?c(g):E(e,b._legacyFed)?(g=l.toJson(),g.server=e.server,g.resources=null,c(new t(g))):(a._pendingDfd=b.generateToken(b.findServerInfo(l.server),null,{serverUrl:a.resUrl_,token:l.token,ssl:l.ssl})).addCallbacks(function(b){c(new t({userId:l.userId,server:e.server,token:b.token,expires:s.isDefined(b.expires)?Number(b.expires):null,ssl:!!b.ssl,isAdmin:a.admin_,validity:b.validity}))},d):(b._busy=null,n&&(a.options_.token=null),(a._pendingDfd=b.getCredential(f.replace(/\/?$/,
"/sharing"),{resource:a.resUrl_,token:n,error:k})).addCallbacks(function(c){b._enqueue(a.resUrl_,a.sinfo_,a.options_,a,a.admin_)},function(a){d(a)}))},f=a.sinfo_.owningSystemUrl,k=this._isServerRsrc(a.resUrl_),q=a.sinfo_._restInfoDfd;q?q.addCallbacks(function(c){var d=a.sinfo_;d.adminTokenServiceUrl=d._restInfoDfd.adminUrl_;d._restInfoDfd=null;d.tokenServiceUrl=m.getObject("authInfo.tokenServicesUrl",!1,c)||m.getObject("authInfo.tokenServiceUrl",!1,c)||m.getObject("tokenServiceUrl",!1,c);d.shortLivedTokenValidity=
m.getObject("authInfo.shortLivedTokenValidity",!1,c);d.currentVersion=c.currentVersion;d.owningTenant=c.owningTenant;if(c=d.owningSystemUrl=c.owningSystemUrl)b._portals.push(c),!d.hasPortal&&l.hasSameOrigin(c,a.resUrl_,!0)&&(d.hasPortal=!0);k&&c?g():e()},function(){a.sinfo_._restInfoDfd=null;var b=Error("Unknown resource - could not find token service endpoint.");b.code="IdentityManagerBase.2";b.log=w.isDebug;d(b)}):k&&f?g():a.sinfo_._selfDfd?(f=function(b){a.sinfo_._selfDfd=null;var c=b&&b.user&&
b.user.username;a.sinfo_.webTierAuth=!!c;e(c,b&&b.allSSL)},a.sinfo_._selfDfd.then(f,f)):e()}});t=F(null,{declaredClass:"esri.Credential",tokenRefreshBuffer:2,constructor:function(a){m.mixin(this,a);this.resources=this.resources||[];s.isDefined(this.creationTime)||(this.creationTime=(new Date).getTime())},refreshToken:function(){var a=this,b=this.resources&&this.resources[0],c=k.id.findServerInfo(this.server),d=c&&c.owningSystemUrl,e=!!d&&"server"===this.scope,g=e&&E(c,k.id._legacyFed),f=e&&k.id.findServerInfo(d),
m,q=(m=z[this.server])&&m[this.userId],r;if(!c.webTierAuth&&(e&&!f&&h.some(k.id.serverInfos,function(a){k.id._isIdProvider(d,a.server)&&(f=a);return!!f}),m=f&&k.id.findCredential(f.server,this.userId),!e||m))if(g)m.refreshToken();else{if(e)r={serverUrl:b,token:m&&m.token,ssl:m&&m.ssl};else if(q)this.isAdmin&&(r={isAdmin:!0});else{var p;b&&(b=k.id._sanitizeUrl(b),this._enqueued=1,p=k.id._enqueue(b,c,null,null,this.isAdmin,this),p.addBoth(function(){a._enqueued=0}));return p}return k.id.generateToken(e?
f:c,e?null:{username:this.userId,password:q},r).addCallback(function(b){a.token=b.token;a.expires=s.isDefined(b.expires)?Number(b.expires):null;a.creationTime=(new Date).getTime();a.validity=b.validity;a.onTokenChange();"portal"===a.scope&&h.forEach(k.id.credentials,function(b){var c=k.id.findServerInfo(b.server),d=c&&c.owningSystemUrl;if(b!==a&&b.userId===a.userId&&d&&"server"===b.scope&&(l.hasSameOrigin(a.server,d,!0)||k.id._isIdProvider(d,a.server)))E(c,k.id._legacyFed)?(b.token=a.token,b.expires=
a.expires,b.creationTime=a.creationTime,b.validity=a.validity,b.onTokenChange()):b.refreshToken()})}).addErrback(function(){})}},onTokenChange:function(a){clearTimeout(this._refreshTimer);var b=this.server&&k.id.findServerInfo(this.server),c=(b=b&&b.owningSystemUrl)&&k.id.findServerInfo(b);!1!==a&&((!b||"portal"===this.scope||c&&c.webTierAuth)&&(s.isDefined(this.expires)||s.isDefined(this.validity)))&&this._startRefreshTimer()},onDestroy:function(){},destroy:function(){this.userId=this.server=this.token=
this.expires=this.validity=this.resources=this.creationTime=null;var a=h.indexOf(k.id.credentials,this);-1<a&&k.id.credentials.splice(a,1);this.onTokenChange();this.onDestroy()},toJson:function(){return this._toJson()},_toJson:function(){var a=s.fixJson({userId:this.userId,server:this.server,token:this.token,expires:this.expires,validity:this.validity,ssl:this.ssl,isAdmin:this.isAdmin,creationTime:this.creationTime,scope:this.scope}),b=this.resources;b&&0<b.length&&(a.resources=b);return a},_startRefreshTimer:function(){clearTimeout(this._refreshTimer);
var a=6E4*this.tokenRefreshBuffer,b=(this.validity?this.creationTime+6E4*this.validity:this.expires)-(new Date).getTime();0>b&&(b=0);this._refreshTimer=setTimeout(m.hitch(this,this.refreshToken),b>a?b-a:b)}});x.Credential=t;J("extend-esri")&&(k.IdentityManagerBase=x,k.Credential=t);return x});