/*
 COPYRIGHT 2009 ESRI

 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.

 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA

 email: contracts@esri.com
 */
//>>built
define("esri/request","dojo/_base/array dojo/_base/config dojo/_base/Deferred dojo/_base/lang dojo/_base/url dojo/_base/xhr dojo/io/script dojo/io/iframe dojo/dom-construct dojo/io-query esri/kernel esri/config esri/sniff esri/lang esri/urlUtils esri/deferredUtils".split(" "),function(x,J,R,n,P,K,V,W,S,T,g,X,q,w,r,Y){function L(a){a=new P(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function y(a,d,e,f){var k=!1,l=!1,t;w.isDefined(d)&&(n.isObject(d)?(k=!!d.useProxy,l=!!d.usePost,t=d.crossOrigin):
k=!!d);a=n.mixin({},a);a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));d=a.content;var m=a.url,h=e&&a.form,s=p;t=w.isDefined(t)?t:s.useCors;a.load=function(a){var b;a&&(a.error?(b=n.mixin(Error(),a.error),b.log=J.isDebug):"error"===a.status&&(b=n.mixin(Error(),a),b.log=J.isDebug),b&&!w.isDefined(b.httpCode)&&(b.httpCode=b.code));return b||a};a.error=function(a,b){b&&b.xhr&&b.xhr.abort();a instanceof Error||(a=n.mixin(Error(),a));a.log=J.isDebug;s.errorHandler(a,b);return a};a._token&&(a.content=
a.content||{},a.content.token=a._token);var z=0;d&&m&&(z=T.objectToQuery(d).length+m.length+1);a.timeout=w.isDefined(a.timeout)?a.timeout:s.timeout;a.handleAs=a.handleAs||"json";try{var u,v,b=t&&r.canUseXhr(a.url)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),c=r.hasSameOrigin(a.url,window.location.href)||b,A=l||e||z>s.postLength?!0:!1,U=!c&&-1!==a.handleAs.indexOf("json")&&a.callbackParamName&&!e?!0:!1,C=r.getProxyRule(a.url)||s.alwaysUseProxy||k||(!U||A)&&!c?!0:!1;e&&(!q("esri-file-upload")&&
!C&&b)&&(C=!0);if(C)if(u=r.getProxyUrl(m,t),v=u.path,u._xo&&(b=!0),!A&&v.length+1+z>s.postLength&&(A=!0),a.url=v+"?"+m,A)a.content=n.mixin(u.query||{},d);else{var y=T.objectToQuery(n.mixin(u.query||{},d));y&&(a.url+="?"+y);a.content=null}if(U&&!A)return!w.isDefined(a.isAsync)&&4>q("ff")&&(a.isAsync=!0),V.get(D?D(a):a);var E=a.headers;if(b&&(!E||!E.hasOwnProperty("X-Requested-With")))E=a.headers=E||{},E["X-Requested-With"]=null;if(e){var M=a.callbackParamName||"callback.html",B=a.callbackElementName||
"textarea",F,N,G,O,H=h.elements?h.elements.length:0,Q;if(d=a.content)for(F in d)if(G=d[F],w.isDefined(G)){N=null;for(O=0;O<H;O++)if(Q=h.elements[O],Q.name===F){N=Q;break}N?N.value=G:f?h.append(F,G):h.appendChild(S.create("input",{type:"hidden",name:F,value:G}))}if(q("esri-file-upload"))x.forEach(h.elements,function(a){a.name===M&&h.removeChild(a)}),a.contentType=!1,a.postData=f?h:new FormData(h),delete a.form;else{h.enctype="multipart/form-data";9>q("ie")&&(h.encoding="multipart/form-data");h.method=
"post";x.some(h.elements,function(a){return a.name===M})||h.appendChild(S.create("input",{type:"hidden",name:M,value:B}));if(-1!==m.toLowerCase().indexOf("addattachment")||-1!==m.toLowerCase().indexOf("updateattachment"))a.url=m+(-1===m.indexOf("?")?"?":"\x26")+M+"\x3d"+B,C&&(a.url=v+"?"+a.url);delete a.content}}if(b&&!a.hasOwnProperty("withCredentials"))if(f=C?v:m,-1!==x.indexOf(p.webTierAuthServers,L(f)))a.withCredentials=!0;else if(g.id){var I=g.id.findServerInfo(f);I&&I.webTierAuth&&(a.withCredentials=
!0)}a=D?D(a):a;return A?e&&!q("esri-file-upload")?W.send(a):K.post(a):K.get(a)}catch(P){return e=new R,e.errback(a.error(P)),e}}function B(a){var d=p._processedCorsServers,e=-1,e=r.canUseXhr(a,!0);-1<e&&p.corsEnabledServers.splice(e,1);d[L(a)]=1;return e}function H(a){var d=p._processedCorsServers;if(p.corsDetection&&p.useCors)try{var e=L(a);q("esri-cors")&&(a&&-1!==a.toLowerCase().indexOf("/rest/services")&&!r.hasSameOrigin(a,window.location.href)&&!r.canUseXhr(a)&&!d[e])&&(d[e]=-1,K.get({url:a.substring(0,
a.toLowerCase().indexOf("/rest/")+6)+"info",content:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null}}).then(function(f){f?(d[e]=2,r.canUseXhr(a)||p.corsEnabledServers.push(e)):d[e]=1},function(a){d[e]=1}))}catch(f){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}}function I(a){D=a}function l(a,d){function e(b){b._pendingDfd=y(a,d,s,h);if(!b._pendingDfd){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;var c=Error("Deferred object is missing");
c.log=J.isDebug;a._usrDfd=null;b.errback(c);b._pendingDfd=null;return b}b._pendingDfd.addCallback(function(d){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;a._usrDfd=null;b.callback(d);b._pendingDfd=null}).addErrback(function(c){if(c&&403==c.code&&(4==c.subcode||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!a._ssl){a._ssl=a._sslFromServer=!0;a._usrDfd=b;l(a,d);return}}else if(c&&415==c.status){if(B(a.url),!a._err415){a._err415=1;a._usrDfd=
b;l(a,d);return}}else if(g.id&&-1!==x.indexOf(g.id._errorCodes,c.code)&&!g.id._isPublic(a.url)&&!n&&(403!=c.code||!w.isDefined(c.subcode)||2==c.subcode)){b._pendingDfd=g.id.getCredential(a.url,{token:a._token,error:c});b._pendingDfd.addCallback(function(c){a._token=c.token;a._usrDfd=b;a._credential=c;a._ssl=a._sslFromServer||c.ssl;l(a,d)}).addErrback(function(c){a._usrDfd=null;b.errback(c);b._pendingDfd=null});return}b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;a._usrDfd=null;b.errback(c);b._pendingDfd=
null})}a.url=r.fixUrl(a.url);var f,k=a.form,n=d&&d.disableIdentityLookup,t=d&&d._preLookup,m=q("esri-workers")&&(d&&!0===d.useWorkers||!0===p.useWorkers),h=k&&k.append,s=k&&(k.elements?x.some(k.elements,function(a){return"file"===a.type}):h),z=-1!==a.url.toLowerCase().indexOf("token\x3d")||a.content&&a.content.token||s&&x.some(k.elements,function(a){return"token"===a.name})?1:0;H(a.url);if(a._usrDfd)f=a._usrDfd;else{f=new R(Y._dfdCanceller);f.addCallback(function(b){/\/sharing\/rest\/accounts\/self/i.test(a.url)&&
(!z&&!a._token&&b.user&&b.user.username)&&p.webTierAuthServers.push(L(a.url));if(b=a._credential){var c=g.id.findServerInfo(b.server);if(c=c&&c.owningSystemUrl)c=c.replace(/\/?$/,"/sharing"),(b=g.id.findCredential(c,b.userId))&&-1===g.id._getIdenticalSvcIdx(c,b)&&b.resources.splice(0,0,c)}});f.addBoth(function(b){delete a._credential;if(b&&(!q("ie")||!b.nodeType))b._ssl=a._ssl});var u=a.load,v=a.error;u&&f.addCallback(function(a){var c=f._pendingDfd,c=c&&c.ioArgs;return u.call(c&&c.args,a,c)});v&&
f.addErrback(function(a){var c=f._pendingDfd,c=c&&c.ioArgs;return v.call(c&&c.args,a,c)})}if(g.id&&!z&&!a._token&&!g.id._isPublic(a.url)&&(!n||t))if(k=g.id.findCredential(a.url))a._token=k.token,a._ssl=k.ssl;m?require(["esri/workers/requestClient"],function(a){K=a;e(f)}):e(f);return f}var D,p=X.defaults.io;l._request=y;l._disableCors=B;l._detectCors=H;l.setRequestPreCallback=I;q("extend-esri")&&(g.request=l,g._request=y,g._disableCors=B,g._detectCors=H,g.setRequestPreCallback=I);return l});